#line 2 "src/Scanner/scanner.c"

#line 4 "src/Scanner/scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 136
#define YY_END_OF_BUFFER 137
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[565] =
    {   0,
        0,    0,  137,  136,  134,   15,  136,   14,   25,  136,
        4,    5,   13,   10,   20,   11,   21,   12,  123,  123,
      123,   18,   19,   23,   22,   24,   16,  136,  122,    8,
        9,   17,  122,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
        6,   26,    7,   27,  135,   31,    0,    0,   36,   42,
       37,    0,    0,    0,    0,    0,   34,   45,   32,   46,
       33,    0,  122,  122,  122,    0,    1,   35,    0,    0,
      123,  123,  125,  124,    0,  125,  124,   40,   30,   28,
       47,   29,   41,   44,    0,    3,    3,    0,  122,   39,

        0,   51,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   65,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   78,    0,   80,   84,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   38,   43,  133,    0,  132,  132,  123,  132,
        0,    0,    0,    0,    0,    0,    0,  122,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        1,  126,  127,  127,   48,   49,    0,    0,    3,    3,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   75,    0,    0,   81,    0,    0,   87,
        0,    0,    0,   91,    0,    0,    0,    0,    0,    0,
       98,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  131,    0,    0,  131,  123,  123,  123,    0,
      131,  123,  123,  132,  122,  122,    0,  131,    0,  122,
        2,    0,  129,  128,  129,  128,    0,    0,   52,   53,
        0,   55,   56,   57,    0,    0,    0,    0,    0,    0,
        0,    0,   67,   68,    0,    0,    0,    0,    0,    0,

        0,   77,    0,    0,   85,   86,   88,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  109,    0,  111,    0,  113,
        0,    0,    0,    0,    0,  119,    0,    0,    0,    0,
        0,    0,  123,  123,    0,    0,    0,  131,    0,  131,
      122,  122,    0,  130,    0,   54,    0,   59,   60,    0,
        0,    0,    0,    0,   69,    0,    0,   72,   73,   74,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  100,    0,  102,    0,    0,    0,    0,    0,
        0,  110,    0,  114,    0,    0,    0,    0,    0,  121,

        0,    0,    0,    0,    0,    0,    0,    0,    0,  131,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       66,    0,   71,    0,    0,    0,    0,   89,    0,    0,
       93,    0,    0,   96,    0,   99,  101,  103,    0,  105,
      106,  107,  108,  112,    0,  116,  117,    0,    0,  131,
        0,    0,  131,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  131,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   58,    0,   62,   63,    0,    0,   76,    0,
        0,    0,    0,    0,   94,    0,    0,    0,    0,  118,

        0,    0,  131,    0,  131,  131,    0,    0,  131,   50,
       61,   64,   70,   79,    0,   83,   90,   92,    0,   97,
        0,    0,  120,    0,    0,    0,    0,    0,    0,    0,
      131,    0,    0,    0,    0,    0,    0,   82,   95,    0,
      115,    0,  131,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  104,    0,  131,    0,    0,    0,    0,
        0,    0,    0,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    1,    5,    6,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,    1,    1,   27,   28,   29,
        1,    1,    1,    1,    1,   30,   31,    1,    1,    1,
        1,    1,    1,    1,   32,    1,    1,   33,    1,   34,
       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
       54,   55,    1,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   65,   66,   67,   68,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[70] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[570] =
    {   0,
        0,    0, 1034, 1035, 1035, 1011,  994, 1009,   64,   64,
     1035, 1035, 1008,   61, 1035,   60,   71,   66,  129,   74,
      112, 1035, 1035,   53,   57,   71, 1005,  134,  159, 1035,
     1035, 1006,  176,   58,   62,   63,   48,   83,  973,  112,
      972,   80,  141,  111,  981,  164,   93,  156,   84,  977,
     1035,  131, 1035, 1035, 1035, 1035, 1019,  116, 1035, 1035,
     1035, 1015,  212, 1014,  208, 1013, 1035, 1035, 1035, 1035,
     1035,  207,  249,  262,  277,  112,    0, 1035,  277,  225,
      316,  319,   95,  125,  298,  120,  176,  997, 1035, 1035,
     1035, 1035,  996, 1035,  978,  340,  343,  977,  372, 1035,

      958, 1035,  957,  959,  968,  953,  953,  174,  969,  955,
      136,  948,  949,  946,  960,  131,  952,  940,  947,  944,
      941, 1035,  943,  939, 1035,   42,  935,  944,  945,  949,
      934,  947,  934,  183,  948,  202,  925,  947,  932,  921,
      214,  936,  147,  924,  927,  928,  926,  215,  932,  922,
      207,  929, 1035, 1035, 1035,  972,  263,  283,    0,  346,
      968,  967,  966,  965,  964,  963,  962,  375,  961,  960,
      959,  958,  957,  956,  955,  954,  953,  952,  272,  943,
        0, 1035,  341,  365, 1035, 1035,  950,  917,  403,  404,
      948,  896,  909,  901,  911,  906,  905,  892,  905,  889,

      163,  897,  904,  899,  901,  897,  888,  886,  887,  893,
      879,  891,  894,  889,  878,  880,  886,  879,  882, 1035,
      876,  882,  869, 1035,  868,  883,  862,  863,  869,  876,
     1035,  859,  859,  865,  859,  870,  267,  214,  855,  855,
      857,  866,  865,  850,  854,  859,  865,  850,  845,  859,
      861,  849,  433,  892,  438,  443,  446,  456,  462,    0,
      475,  891,  488, 1035,  496,  509,  326,  409,  483,  524,
     1035,  859,  212,  223,  260,  256,  889,  839, 1035, 1035,
      844, 1035, 1035, 1035,  843,  835,  833,  842,  837,  829,
      841,  835, 1035, 1035,  827,  836,  827,  838,  838,  822,

      839, 1035,  830,  821, 1035, 1035, 1035,  834,  835,  818,
      821,  832,  827,  822,  815,  812,  823,  822,  807,  810,
      813,  814,  808,  818,  817, 1035,  797, 1035,  803, 1035,
      810,  811,  809,  797,  793, 1035,  793,  806,  524,  417,
      563,  510,  842,  568,  614,  562,  581,  530,  332,  547,
      597,  622,  838, 1035,  807, 1035,  802, 1035, 1035,  792,
      804,  792,  802,  797, 1035,  798,  786, 1035, 1035, 1035,
      796,  795,  323,  778,  777,  786,  776,  772,  787,  786,
      774,  773, 1035,  778, 1035,  775,  779,  776,  747,  732,
      742, 1035,  743, 1035,  736,  733,  718,  723,  711, 1035,

      740,  735,  717,  714,  713,  712,  708,  706,  673,  585,
      701,  699,  692,  690,  686,  678,  677,  676,  624,  656,
      670,  651,  683,  375,  623,  617,  595,  599,  591,  589,
     1035,  598, 1035,  597,  591,  595,  594, 1035,  568,  578,
     1035,  574,  559, 1035,  565, 1035, 1035, 1035,  551, 1035,
     1035, 1035, 1035, 1035,  547, 1035, 1035,  545,  544, 1035,
      657,  722,  467,  674,  587,  580,  576,  571,  567,  565,
      564,  559,  691,  482,  555,  552,  550,  549,  538,  534,
      384,  476, 1035,  489, 1035, 1035,  488,  471, 1035,  461,
      469,  458,  452,  443, 1035,  440,  414,  424,  427, 1035,

      426,  374,  716,  389,  730, 1035,  738,  712, 1035, 1035,
     1035, 1035, 1035, 1035,  422, 1035, 1035, 1035,  422, 1035,
      404,  405, 1035,  754,  439,  742,  768,  435,  752,  401,
      784,  434,  427,  425,  421,  419,  398, 1035, 1035,  361,
     1035,  715,  785,  744,  377,  365,  358,  348,  345,  324,
      798,  321,  779, 1035,  780, 1035,  799,  311,  308,  291,
      287,  278,  238, 1035,  183,  171,  157,  114,   95
    } ;

static yyconst flex_int16_t yy_def[570] =
    {   0,
      564,    1,  564,  564,  564,  564,  565,  564,  564,  566,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  567,  564,  564,  564,  564,  568,  564,  567,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,

      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  569,   19,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      568,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,

      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  569,  564,   19,  564,  564,  569,
      564,  257,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,

      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      569,  564,   19,  564,  567,  567,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,

      564,  564,  564,  564,  564,  564,  564,  564,  567,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,

      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,    0,  564,  564,  564,  564,  564
    } ;

static yyconst flex_uint16_t yy_nxt[1105] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,    4,    4,    4,    4,
        4,    4,    4,   29,   30,    4,   31,   32,    4,   33,
       34,   35,   36,   37,   38,   39,    4,   40,    4,    4,
       41,    4,   42,   43,   44,   45,   46,   47,   48,   49,
       50,    4,    4,   29,   51,   52,   53,   54,   55,   60,
       63,   68,   70,   88,   89,   76,   64,   72,   90,   91,
       77,   71,   69,  218,   73,   61,   74,   78,   74,   82,
       82,   82,   92,   93,  219,  254,   75,  103,  113,   65,

      114,  107,   66,   83,   75,   84,  111,  115,  108,  116,
       75,  104,  109,  105,  181,  110,  112,  156,   79,  155,
      106,  179,  117,  127,   86,   80,  182,   81,   82,   81,
      118,  150,   87,  119,   75,   79,  120,  151,  128,  143,
       95,   83,   80,   84,   81,   82,   81,   96,  144,  180,
      133,  182,  153,  182,  182,  145,  122,  169,   83,   97,
       84,   85,   86,  123,  124,   98,  134,   97,  125,  135,
       87,   62,   99,   97,   75,  182,   75,  202,  182,   86,
      203,  129,   98,   57,   75,  209,  204,   87,  210,   99,
       85,   75,   75,   75,  240,  130,  154,   97,   75,  131,

      132,   75,  241,  146,  137,  182,  147,  138,  148,   75,
      139,  140,  149,  198,  157,   75,  101,  199,  158,  287,
      288,  141,   75,  161,  142,   80,  182,  159,   82,   81,
      227,   79,  102,  170,  171,  172,  228,  173,   80,   75,
       80,  230,   80,  354,  556,  174,  231,  162,  163,  175,
      176,  177,  354,  237,  250,   72,  246,  251,  178,  232,
      164,  323,   73,  165,   74,  166,   74,  167,   72,  238,
      354,  247,  324,  354,   75,   73,  253,   74,  253,   74,
      253,  179,   75,   98,  556,  354,  271,   75,   75,  255,
       99,  354,   75,  556,   75,   75,  256,  556,  257,  258,

      259,   75,   75,  170,  171,  172,  354,  173,  321,  180,
       75,  183,   75,  184,  556,  184,   75,  556,  354,  175,
      176,  177,   79,  184,  322,   75,  184,  557,  178,   80,
      556,   81,   82,   81,   82,   82,   82,  184,  420,  348,
       75,  348,  184,  348,  421,   83,  188,   84,   83,  188,
       84,  556,  260,  189,  556,  190,  189,  190,  190,  261,
      190,  262,   82,  263,  556,  190,   86,  436,  190,   86,
      273,  556,  274,  190,   87,  437,  190,   87,   98,  190,
      524,   98,  190,  556,  481,   99,  525,   75,  265,   75,
      266,  275,  266,  481,  273,  527,  274,   75,  271,  276,

       75,  528,  554,  190,  509,   75,  190,  551,   75,  188,
      188,   75,  180,  552,   75,  275,  189,  189,  190,  190,
      190,  190,  348,  276,  348,  509,  348,  509,  190,  190,
      253,  509,  253,  509,  253,   75,  190,  190,   75,  339,
      509,  544,  190,  190,  341,  542,  253,  541,  253,  345,
      253,  342,  345,  343,  258,  344,  261,  540,  261,  261,
      261,  263,  340,  263,  539,  538,  190,  190,  345,  523,
      522,   82,   82,   82,  521,  261,  520,  263,   82,  263,
      348,  346,  348,  519,  348,   83,  518,   84,  261,  349,
      261,   83,  261,   84,  346,  473,  350,  473,  350,  473,

      350,  261,  347,  263,   82,  263,   86,  517,  516,  265,
      515,  266,   86,  266,   87,  347,  409,   83,  514,   84,
       87,   75,  265,   80,  266,   80,  266,   80,  513,   75,
       98,  512,  511,  510,   75,   75,  419,  351,   86,  352,
      509,  352,   75,  348,  509,  348,   87,  348,   75,   75,
      401,  402,  403,  422,  404,  509,  509,   75,  509,   75,
      350,  509,  350,   75,  350,  506,  405,  406,  407,  341,
      506,  507,   75,  506,  409,  408,  256,  506,  257,  258,
      259,   80,  506,   81,   82,   81,  507,   75,  411,  412,
      413,  462,  414,  506,  501,  500,  499,   83,  253,   84,

      253,  498,  253,  423,  415,  416,  417,  401,  402,  403,
      351,  404,  352,  418,  352,  497,  496,  495,   86,  191,
      494,  493,   75,  405,  406,  407,   87,  410,  423,  410,
       75,  410,  408,  492,  491,  351,   75,  352,  490,  352,
      411,  412,  413,  489,  414,  488,  487,   75,  486,  485,
      465,  466,  467,  484,  468,   75,  415,  416,  417,  483,
       75,   75,  420,  502,  482,  418,  469,  470,  471,  473,
      503,  473,  503,  473,  503,  472,  474,  475,  466,  476,
      504,  477,  463,  463,  464,   75,  410,  505,  410,  505,
      410,  505,  463,  478,  470,  479,  463,  508,  463,  170,

      171,  172,  480,  173,  473,  464,  473,  463,  473,  465,
      466,  467,  460,  468,  460,  175,  176,  177,  461,  460,
      460,  191,  526,  460,  178,  469,  470,  471,  503,  503,
      503,  503,  503,  503,  472,  348,  529,  348,  532,  348,
      533,  461,  534,  505,  530,  505,  460,  505,  401,  402,
      403,  531,  404,  531,  535,  531,  536,  543,  459,  543,
      524,  543,  458,  537,  405,  406,  407,  503,  401,  503,
      403,  503,  404,  408,  527,  457,  456,  455,  545,  466,
      546,  543,  547,  543,  405,  543,  407,  454,  453,  452,
      553,  555,  451,  408,  548,  470,  549,  531,  543,  531,

      543,  531,  543,  550,  551,  465,  558,  467,  559,  468,
      560,  531,  531,  531,  531,  531,  531,  450,  449,  448,
      447,  469,  561,  471,  562,  446,  445,  444,  443,  442,
      472,  563,  441,  440,  439,  438,  435,  434,  433,  432,
      431,  430,  429,  428,  427,  426,  425,  424,  409,  400,
      399,  398,  397,  396,  395,  394,  393,  392,  391,  390,
      389,  388,  387,  386,  385,  384,  383,  382,  381,  380,
      379,  378,  377,  376,  375,  374,  373,  372,  371,  370,
      369,  368,  367,  366,  365,  364,  363,  362,  361,  360,
      359,  358,  357,  356,  355,  190,  353,  346,  340,  338,

      337,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  320,  319,  318,  317,  316,  315,  314,
      313,  312,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  286,  285,  284,  283,  282,
      281,  280,  279,  278,   75,  277,   97,  272,  268,  268,
      269,  268,  270,  268,  268,  269,  268,  267,  264,  264,
      264,  264,  264,  264,  264,  155,  252,  249,  248,  245,
      244,  243,  242,  239,  236,  235,  234,  233,  229,  226,
      225,  224,  223,  222,  221,  220,  217,  216,  215,  214,

      213,  212,  211,  208,  207,  206,  205,  201,  200,  197,
      196,  195,  194,  193,  192,  191,  187,  186,  185,  168,
      160,  157,  155,  152,  136,  126,  121,  100,   94,   67,
       59,   58,   56,  564,    3,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,

      564,  564,  564,  564
    } ;

static yyconst flex_int16_t yy_chk[1105] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    9,
       10,   14,   16,   24,   24,   18,   10,   17,   25,   25,
       18,   16,   14,  126,   17,    9,   17,   18,   17,   20,
       20,   20,   26,   26,  126,  569,   17,   34,   37,   10,

       37,   35,   10,   20,   17,   20,   36,   37,   35,   37,
       17,   34,   35,   34,  568,   35,   36,   58,   21,   58,
       34,   76,   38,   42,   20,   21,   83,   21,   21,   21,
       38,   49,   20,   38,   17,   19,   38,   49,   42,   47,
       28,   21,   19,   21,   19,   19,   19,   28,   47,   76,
       44,   86,   52,   83,   84,   47,   40,  567,   19,   28,
       19,   19,   21,   40,   40,   29,   44,   28,   40,   44,
       21,  566,   29,   28,   29,   84,   29,  111,   86,   19,
      111,   43,   33,  565,   29,  116,  111,   19,  116,   33,
       19,   33,   29,   33,  143,   43,   52,   28,   29,   43,

       43,   33,  143,   48,   46,   87,   48,   46,   48,   33,
       46,   46,   48,  108,   65,   33,   33,  108,   63,  201,
      201,   46,   29,   65,   46,   63,   87,   63,   63,   63,
      134,   80,   33,   72,   72,   72,  134,   72,   80,   33,
       80,  136,   80,  273,  563,   72,  136,   65,   65,   72,
       72,   72,  274,  141,  151,   73,  148,  151,   72,  136,
       65,  238,   73,   65,   73,   65,   73,   65,   74,  141,
      273,  148,  238,  274,   73,   74,  157,   74,  157,   74,
      157,  179,   73,   75,  562,  276,  179,   74,   73,  158,
       75,  275,   75,  561,   75,   74,  158,  560,  158,  158,

      158,   74,   75,   79,   79,   79,  276,   79,  237,  179,
       75,   85,   73,   85,  559,   85,   75,  558,  275,   79,
       79,   79,   81,   85,  237,   74,   85,  552,   79,   81,
      550,   81,   81,   81,   82,   82,   82,   85,  349,  267,
       75,  267,   85,  267,  349,   81,   96,   81,   82,   97,
       82,  549,  160,   96,  548,   96,   97,   96,   97,  160,
       97,  160,  160,  160,  547,   96,   81,  373,   97,   82,
      183,  546,  183,   96,   81,  373,   97,   82,   99,   96,
      502,  168,   97,  545,  424,   99,  502,   99,  168,   99,
      168,  183,  168,  481,  184,  504,  184,   99,  481,  183,

      168,  504,  540,   96,  537,   99,   97,  530,  168,  189,
      190,   99,  424,  530,  168,  184,  189,  190,  189,  190,
      189,  190,  268,  184,  268,  536,  268,  535,  189,  190,
      340,  534,  340,  533,  340,   99,  189,  190,  168,  253,
      532,  528,  189,  190,  255,  525,  253,  522,  253,  256,
      253,  255,  257,  255,  255,  255,  256,  521,  256,  257,
      256,  257,  258,  257,  519,  515,  189,  190,  259,  501,
      499,  258,  258,  258,  498,  259,  497,  259,  259,  259,
      463,  261,  463,  496,  463,  258,  494,  258,  261,  269,
      261,  259,  261,  259,  263,  474,  269,  474,  269,  474,

      269,  263,  265,  263,  263,  263,  258,  493,  492,  265,
      491,  265,  259,  265,  258,  266,  342,  263,  490,  263,
      259,  265,  266,  342,  266,  342,  266,  342,  488,  265,
      270,  487,  484,  482,  266,  265,  348,  270,  263,  270,
      480,  270,  266,  348,  479,  348,  263,  348,  266,  270,
      339,  339,  339,  350,  339,  478,  477,  270,  476,  265,
      350,  475,  350,  270,  350,  472,  339,  339,  339,  341,
      471,  470,  266,  469,  344,  339,  341,  468,  341,  341,
      341,  344,  467,  344,  344,  344,  466,  270,  346,  346,
      346,  410,  346,  465,  459,  458,  455,  344,  410,  344,

      410,  449,  410,  351,  346,  346,  346,  347,  347,  347,
      351,  347,  351,  346,  351,  445,  443,  442,  344,  347,
      440,  439,  351,  347,  347,  347,  344,  345,  352,  345,
      351,  345,  347,  437,  436,  352,  351,  352,  435,  352,
      345,  345,  345,  434,  345,  432,  430,  352,  429,  428,
      419,  419,  419,  427,  419,  352,  345,  345,  345,  426,
      351,  352,  420,  461,  425,  345,  419,  419,  419,  420,
      461,  420,  461,  420,  461,  419,  421,  422,  422,  422,
      464,  422,  418,  417,  416,  352,  409,  464,  409,  464,
      409,  464,  415,  422,  422,  422,  414,  473,  413,  409,

      409,  409,  422,  409,  473,  412,  473,  411,  473,  423,
      423,  423,  408,  423,  407,  409,  409,  409,  406,  405,
      404,  423,  503,  403,  409,  423,  423,  423,  542,  503,
      542,  503,  542,  503,  423,  462,  505,  462,  508,  462,
      508,  402,  508,  505,  507,  505,  401,  505,  462,  462,
      462,  507,  462,  507,  508,  507,  508,  544,  399,  544,
      524,  544,  398,  508,  462,  462,  462,  524,  526,  524,
      526,  524,  526,  462,  527,  397,  396,  395,  529,  529,
      529,  527,  529,  527,  526,  527,  526,  393,  391,  390,
      531,  543,  389,  526,  529,  529,  529,  531,  543,  531,

      543,  531,  543,  529,  551,  553,  555,  553,  555,  553,
      555,  551,  557,  551,  557,  551,  557,  388,  387,  386,
      384,  553,  555,  553,  555,  382,  381,  380,  379,  378,
      553,  555,  377,  376,  375,  374,  372,  371,  367,  366,
      364,  363,  362,  361,  360,  357,  355,  353,  343,  338,
      337,  335,  334,  333,  332,  331,  329,  327,  325,  324,
      323,  322,  321,  320,  319,  318,  317,  316,  315,  314,
      313,  312,  311,  310,  309,  308,  304,  303,  301,  300,
      299,  298,  297,  296,  295,  292,  291,  290,  289,  288,
      287,  286,  285,  281,  278,  277,  272,  262,  254,  252,

      251,  250,  249,  248,  247,  246,  245,  244,  243,  242,
      241,  240,  239,  236,  235,  234,  233,  232,  230,  229,
      228,  227,  226,  225,  223,  222,  221,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  191,  188,  187,  180,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  169,  167,  166,
      165,  164,  163,  162,  161,  156,  152,  150,  149,  147,
      146,  145,  144,  142,  140,  139,  138,  137,  135,  133,
      132,  131,  130,  129,  128,  127,  124,  123,  121,  120,

      119,  118,  117,  115,  114,  113,  112,  110,  109,  107,
      106,  105,  104,  103,  101,   98,   95,   93,   88,   66,
       64,   62,   57,   50,   45,   41,   39,   32,   27,   13,
        8,    7,    6,    3,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  564,  564,  564,  564,  564,  564,  564,  564,  564,

      564,  564,  564,  564
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/Scanner/c-sharp.l"
/* Scanner for a C# 6.0 compiler generated with Flex */
#define YY_NO_INPUT 1
#line 8 "src/Scanner/c-sharp.l"

#include "pch.h"
#include "parser.h"

#define SBYTE_MAX_VALUE  127
#define BYTE_MAX_VALUE   256
#define SHORT_MAX_VALUE  32767
#define USHORT_MAX_VALUE 65535
#define INT_MAX_VALUE    2147483647
#define UINT_MAX_VALUE   4294967295
#define LONG_MAX_VALUE   9223372036854775807

int CheckIntType(long long value, char *suffix);
long long TreatIntString(char *text);
long long TreatHexString(char *text);
int CheckRealType(char *text);

/* character_literal '\''{character}'\''

character .|{simple_escape_sequence}|{hexadecimal_escape_sequence}

simple_escape_sequence '\\\''|'\\"'|'\\\\'|'\\0'|'\\a'|'\\b'|'\\f'|'\\n'|'\\r'|'\\t'|'\\v'

hexadecimal_escape_sequence "\\x"([0..9]|[a..f]|[A..F])([0..9]|[a..f]|[A..F])?([0..9]|[a..f]|[A..F])?([0..9]|[a..f]|[A..F])? */
#line 927 "src/Scanner/scanner.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 49 "src/Scanner/c-sharp.l"


#line 1146 "src/Scanner/scanner.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 565 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1035 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 51 "src/Scanner/c-sharp.l"
{ /* singleline comments are ignored*/ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 52 "src/Scanner/c-sharp.l"
{ /* multiline comments are ignored */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 54 "src/Scanner/c-sharp.l"
{ printf("IDENTIFIER\n");return IDENTIFIER; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 56 "src/Scanner/c-sharp.l"
{ printf("START_PAR\n");return START_PAR; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 57 "src/Scanner/c-sharp.l"
{ printf("END_PAR\n");return END_PAR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 58 "src/Scanner/c-sharp.l"
{ printf("START_CURLY\n");return START_CURLY; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 59 "src/Scanner/c-sharp.l"
{ printf("END_CURLY\n");return END_CURLY; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 60 "src/Scanner/c-sharp.l"
{ printf("START_BRCKT\n");return START_BRCKT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 61 "src/Scanner/c-sharp.l"
{ printf("END_BRCKT\n");return END_BRCKT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 62 "src/Scanner/c-sharp.l"
{ printf("ADD\n");return ADD; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 63 "src/Scanner/c-sharp.l"
{ printf("SUB\n");return SUB; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 64 "src/Scanner/c-sharp.l"
{ printf("DIV\n");return DIV; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 65 "src/Scanner/c-sharp.l"
{ printf("MUL\n");return MUL; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 66 "src/Scanner/c-sharp.l"
{ printf("MOD\n");return MOD; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 67 "src/Scanner/c-sharp.l"
{ printf("NOT\n");return NOT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 68 "src/Scanner/c-sharp.l"
{ printf("QMARK\n");return QMARK; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 69 "src/Scanner/c-sharp.l"
{ printf("CIRCUMFLEX\n");return CIRCUMFLEX; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 70 "src/Scanner/c-sharp.l"
{ printf("COLON\n");return COLON; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 71 "src/Scanner/c-sharp.l"
{ printf("SEMI\n");return SEMI; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 72 "src/Scanner/c-sharp.l"
{ printf("COMMA\n");return COMMA; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 73 "src/Scanner/c-sharp.l"
{ printf("DOT\n");return DOT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 74 "src/Scanner/c-sharp.l"
{ printf("ASSIGN\n");return ASSIGN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 75 "src/Scanner/c-sharp.l"
{ printf("LESS_THEN\n");return LESS_THEN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 76 "src/Scanner/c-sharp.l"
{ printf("GREATER_THEN\n");return GREATER_THEN; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 77 "src/Scanner/c-sharp.l"
{ printf("BIT_AND\n");return BIT_AND; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 78 "src/Scanner/c-sharp.l"
{ printf("BIT_OR\n");return BIT_OR; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 79 "src/Scanner/c-sharp.l"
{ printf("BIT_NOT\n");return BIT_NOT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 80 "src/Scanner/c-sharp.l"
{ printf("EQ\n");return EQ; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 81 "src/Scanner/c-sharp.l"
{ printf("GEQ\n");return GEQ; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 82 "src/Scanner/c-sharp.l"
{ printf("LEQ\n");return LEQ; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 83 "src/Scanner/c-sharp.l"
{ printf("NOT_EQ\n");return NOT_EQ; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 84 "src/Scanner/c-sharp.l"
{ printf("ADD_ASSIGN\n");return ADD_ASSIGN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 85 "src/Scanner/c-sharp.l"
{ printf("SUB_ASSIGN\n");return SUB_ASSIGN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 86 "src/Scanner/c-sharp.l"
{ printf("MUL_ASSIGN\n");return MUL_ASSIGN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 87 "src/Scanner/c-sharp.l"
{ printf("DIV_ASSIGN\n");return DIV_ASSIGN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 88 "src/Scanner/c-sharp.l"
{ printf("MOD_ASSIGN\n");return MOD_ASSIGN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 89 "src/Scanner/c-sharp.l"
{ printf("BIT_AND_ASSIGN\n");return BIT_AND_ASSIGN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 90 "src/Scanner/c-sharp.l"
{ printf("BIT_OR_ASSIGN\n");return BIT_OR_ASSIGN; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 91 "src/Scanner/c-sharp.l"
{ printf("CIRCUMFLEX_ASSIGN\n");return CIRCUMFLEX_ASSIGN; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 92 "src/Scanner/c-sharp.l"
{ printf("LEFT_SHIFT\n");return LEFT_SHIFT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 93 "src/Scanner/c-sharp.l"
{ printf("RIGHT_SHIFT\n");return RIGHT_SHIFT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 94 "src/Scanner/c-sharp.l"
{ printf("AND\n");return AND; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 95 "src/Scanner/c-sharp.l"
{ printf("OR\n");return OR; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 96 "src/Scanner/c-sharp.l"
{ printf("DOUBLE_QMARK\n");return DOUBLE_QMARK; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 97 "src/Scanner/c-sharp.l"
{ printf("INCREMENT\n");return INCREMENT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 98 "src/Scanner/c-sharp.l"
{ printf("DECREMENT\n");return DECREMENT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 99 "src/Scanner/c-sharp.l"
{ printf("LAMBDA\n");return LAMBDA; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 100 "src/Scanner/c-sharp.l"
{ printf("LEFT_SHIFT_ASSIGN\n");return LEFT_SHIFT_ASSIGN; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 101 "src/Scanner/c-sharp.l"
{ printf("RIGHT_SHIFT_ASSIGN\n");return RIGHT_SHIFT_ASSIGN; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 102 "src/Scanner/c-sharp.l"
{ printf("ABSTRACT\n");return ABSTRACT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 103 "src/Scanner/c-sharp.l"
{ printf("AS\n");return AS; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 104 "src/Scanner/c-sharp.l"
{ printf("BASE\n");return BASE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 105 "src/Scanner/c-sharp.l"
{ printf("BOOL_TYPE\n");return BOOL_TYPE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 106 "src/Scanner/c-sharp.l"
{ printf("BREAK\n");return BREAK; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 107 "src/Scanner/c-sharp.l"
{ printf("BYTE_TYPE\n");return BYTE_TYPE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 108 "src/Scanner/c-sharp.l"
{ printf("CASE\n");return CASE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 109 "src/Scanner/c-sharp.l"
{ printf("CHAR_TYPE\n");return CHAR_TYPE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 110 "src/Scanner/c-sharp.l"
{ printf("CHECKED\n");return CHECKED; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 111 "src/Scanner/c-sharp.l"
{ printf("CLASS\n");return CLASS; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 112 "src/Scanner/c-sharp.l"
{ printf("CONST\n");return CONST; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 113 "src/Scanner/c-sharp.l"
{ printf("CONTINUE\n");return CONTINUE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 114 "src/Scanner/c-sharp.l"
{ printf("DECIMAL_TYPE\n");return DECIMAL_TYPE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 115 "src/Scanner/c-sharp.l"
{ printf("DEFAULT\n");return DEFAULT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 116 "src/Scanner/c-sharp.l"
{ printf("DELEGATE\n");return DELEGATE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 117 "src/Scanner/c-sharp.l"
{ printf("DO\n");return DO; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 118 "src/Scanner/c-sharp.l"
{ printf("DOUBLE_TYPE\n");return DOUBLE_TYPE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 119 "src/Scanner/c-sharp.l"
{ printf("ELSE\n");return ELSE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 120 "src/Scanner/c-sharp.l"
{ printf("ENUM\n");return ENUM; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 121 "src/Scanner/c-sharp.l"
{ printf("EVENT\n");return EVENT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 122 "src/Scanner/c-sharp.l"
{ printf("EXPLICIT\n");return EXPLICIT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 123 "src/Scanner/c-sharp.l"
{ printf("EXTERN\n");return EXTERN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 124 "src/Scanner/c-sharp.l"
{ printf("FALSE_VAL\n");return FALSE_VAL; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 125 "src/Scanner/c-sharp.l"
{ printf("FIXED\n");return FIXED; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 126 "src/Scanner/c-sharp.l"
{ printf("FLOAT_TYPE\n");return FLOAT_TYPE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 127 "src/Scanner/c-sharp.l"
{ printf("FOR\n");return FOR; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 128 "src/Scanner/c-sharp.l"
{ printf("FOREACH\n");return FOREACH; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 129 "src/Scanner/c-sharp.l"
{ printf("GOTO\n");return GOTO; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 130 "src/Scanner/c-sharp.l"
{ printf("IF\n");return IF; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 131 "src/Scanner/c-sharp.l"
{ printf("IMPLICIT\n");return IMPLICIT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 132 "src/Scanner/c-sharp.l"
{ printf("IN\n");return IN; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 133 "src/Scanner/c-sharp.l"
{ printf("INT_TYPE\n");return INT_TYPE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 134 "src/Scanner/c-sharp.l"
{ printf("INTERFACE\n");return INTERFACE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 135 "src/Scanner/c-sharp.l"
{ printf("INTERNAL\n");return INTERNAL; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 136 "src/Scanner/c-sharp.l"
{ printf("IS\n");return IS; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 137 "src/Scanner/c-sharp.l"
{ printf("LOCK\n");return LOCK; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 138 "src/Scanner/c-sharp.l"
{ printf("LONG_TYPE\n");return LONG_TYPE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 139 "src/Scanner/c-sharp.l"
{ printf("NEW\n");return NEW; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 140 "src/Scanner/c-sharp.l"
{ printf("NULL_VALUE\n");return NULL_VALUE; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 141 "src/Scanner/c-sharp.l"
{ printf("OBJECT\n");return OBJECT; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 142 "src/Scanner/c-sharp.l"
{ printf("OPERATOR\n");return OPERATOR; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 143 "src/Scanner/c-sharp.l"
{ printf("OUT\n");return OUT; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 144 "src/Scanner/c-sharp.l"
{ printf("OVERRIDE\n");return OVERRIDE; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 145 "src/Scanner/c-sharp.l"
{ printf("PARAMS\n");return PARAMS; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 146 "src/Scanner/c-sharp.l"
{ printf("PRIVATE\n");return PRIVATE; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 147 "src/Scanner/c-sharp.l"
{ printf("PROTECTED\n");return PROTECTED; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 148 "src/Scanner/c-sharp.l"
{ printf("PUBLIC\n");return PUBLIC; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 149 "src/Scanner/c-sharp.l"
{ printf("READONLY\n");return READONLY; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 150 "src/Scanner/c-sharp.l"
{ printf("REF\n");return REF; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 151 "src/Scanner/c-sharp.l"
{ printf("RETURN\n");return RETURN; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 152 "src/Scanner/c-sharp.l"
{ printf("SBYTE_TYPE\n");return SBYTE_TYPE; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 153 "src/Scanner/c-sharp.l"
{ printf("SEALED\n");return SEALED; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 154 "src/Scanner/c-sharp.l"
{ printf("SHORT_TYPE\n");return SHORT_TYPE; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 155 "src/Scanner/c-sharp.l"
{ printf("SIZEOF\n");return SIZEOF; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 156 "src/Scanner/c-sharp.l"
{ printf("STACKALLOC\n");return STACKALLOC; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 157 "src/Scanner/c-sharp.l"
{ printf("STATIC\n");return STATIC; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 158 "src/Scanner/c-sharp.l"
{ printf("STRING_TYPE\n");return STRING_TYPE; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 159 "src/Scanner/c-sharp.l"
{ printf("STRUCT\n");return STRUCT; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 160 "src/Scanner/c-sharp.l"
{ printf("SWITCH\n");return SWITCH; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 161 "src/Scanner/c-sharp.l"
{ printf("THIS\n");return THIS; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 162 "src/Scanner/c-sharp.l"
{ printf("THROW\n");return THROW; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 163 "src/Scanner/c-sharp.l"
{ printf("TRUE_VAL\n");return TRUE_VAL; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 164 "src/Scanner/c-sharp.l"
{ printf("TYPEOF\n");return TYPEOF; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 165 "src/Scanner/c-sharp.l"
{ printf("UINT_TYPE\n");return UINT_TYPE; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 166 "src/Scanner/c-sharp.l"
{ printf("ULONG_TYPE\n");return ULONG_TYPE; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 167 "src/Scanner/c-sharp.l"
{ printf("UNCHECKED\n");return UNCHECKED; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 168 "src/Scanner/c-sharp.l"
{ printf("UNSAFE\n");return UNSAFE; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 169 "src/Scanner/c-sharp.l"
{ printf("USHORT_TYPE\n");return USHORT_TYPE; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 170 "src/Scanner/c-sharp.l"
{ printf("VIRTUAL\n");return VIRTUAL; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 171 "src/Scanner/c-sharp.l"
{ printf("VOID\n");return VOID; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 172 "src/Scanner/c-sharp.l"
{ printf("VOLATILE\n");return VOLATILE; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 173 "src/Scanner/c-sharp.l"
{ printf("WHILE\n");return WHILE; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 175 "src/Scanner/c-sharp.l"
{ printf("IDENTIFIER\n");return IDENTIFIER; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 177 "src/Scanner/c-sharp.l"
{ long long value = atoll(yytext); return CheckIntType(value, NULL); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 178 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatIntString(yytext)); return CheckIntType(value, "U"); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 179 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatIntString(yytext)); return CheckIntType(value, "L"); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 180 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatIntString(yytext)); return CheckIntType(value, "UL"); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 182 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatHexString(yytext)); return CheckIntType(value, NULL); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 183 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatHexString(yytext)); return CheckIntType(value, "U"); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 184 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatHexString(yytext)); return CheckIntType(value, "L"); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 185 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatHexString(yytext)); return CheckIntType(value, "UL"); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 187 "src/Scanner/c-sharp.l"
{ return CheckRealType(yytext); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 189 "src/Scanner/c-sharp.l"
{ return CHAR_VAL; }
	YY_BREAK
case 133:
/* rule 133 can match eol */
YY_RULE_SETUP
#line 191 "src/Scanner/c-sharp.l"
{ return STRING_VAL; }
	YY_BREAK
case 134:
/* rule 134 can match eol */
YY_RULE_SETUP
#line 193 "src/Scanner/c-sharp.l"
{ return ENTER; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 194 "src/Scanner/c-sharp.l"
{ return END_OF_FILE; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 196 "src/Scanner/c-sharp.l"
ECHO;
	YY_BREAK
#line 1885 "src/Scanner/scanner.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 69);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 565 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 69;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 565 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 564);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 196 "src/Scanner/c-sharp.l"



int CheckIntType(long long value, char *suffix)
{
    value = llabs(value);

    // If there's no suffix telling which type it is:
    if (suffix == NULL)
    {
        // Comparing the value with the maximum size of each type to define the type that must be returned:
        if (value <= SBYTE_MAX_VALUE)
        {
            printf("SBYTE_VAL\n");
            return SBYTE_VAL;
        }
        else if (value <= BYTE_MAX_VALUE)
        {
            printf("BYTE_VAL\n");
            return BYTE_VAL;
        }
        else if (value <= SHORT_MAX_VALUE)
        {
            printf("SHORT_VAL\n");
            return SHORT_VAL;
        }
        else if (value <= USHORT_MAX_VALUE)
        {
            printf("USHORT_VAL\n");
            return USHORT_VAL;
        }
        else if (value <= INT_MAX_VALUE)
        {
            printf("INT_VAL\n");
            return INT_VAL;
        }
        else if (value <= UINT_MAX_VALUE)
        {
            printf("UINT_VAL\n");
            return UINT_VAL;
        }
        else if (value <= LONG_MAX_VALUE)
        {
            printf("LONG_VAL\n");
            return LONG_VAL;
        }
        else
        {
            printf("ULONG_VALUE\n");
            return ULONG_VAL;
        }
    }
    else if (strcmp(suffix, "U") == 0)
        goto start_from_unsigned;
    else if (strcmp(suffix, "L") == 0)
        goto start_from_long;
    else if (strcmp(suffix, "Ul") == 0)
        goto start_from_unsigned;

    start_from_unsigned:
    if (value <= UINT_MAX_VALUE)
    {
        printf("UINT_VAL\n");
        return UINT_VAL;
    }
    
    start_from_long:
    if (value > UINT_MAX_VALUE)
    {
        printf("LONG_VAL\n");
        return LONG_VAL;
    }
    
    start_from_ulong:
    if (value > LONG_MAX_VALUE)
    {
        printf("ULONG_VALUE\n");
        return ULONG_VAL;
    }

    return -1;
}

#define IS_SIGN(c) (c == '+' || c == '-')
#define IS_DIGIT(c) ('0' <= c && c <= '9')
#define IS_HIGHCASE_HEX(c) ('A' <= c && c <= 'F')
#define IS_LOWCASE_HEX(c) ('a' <= c && c <= 'f')
#define CONVERT_HIGHCASE_HEX(c) (c - 55)
#define CONVERT_LOWCASE_HEX(c) (c - 87)

long long TreatIntString(char *text)
{
    char *letterPtr = text;
    int digits = 0;
    while (IS_DIGIT(*letterPtr) || IS_SIGN(*letterPtr))
    {
        ++digits;
        ++letterPtr;
    }
    char *number = malloc(digits * sizeof(char));
    number = strncpy(number, text, digits * sizeof(char));
    long long result = atoll(number);
    free(number);
    return result;
}

long long TreatHexString(char *text)
{
    char *letter = text;
    int digits = 0;
    long long result = 0;
    while (IS_DIGIT(*letter) || IS_HIGHCASE_HEX(*letter) || IS_LOWCASE_HEX(*letter) || *letter == 'x' || *letter == 'X' || IS_SIGN(*letter))
    {
        ++digits;
        ++letter;
    }
    char *number = malloc(digits * sizeof(char));
    number = strncpy(number, text, digits * sizeof(char));
    result = (long long)strtol(number, NULL, 0);
    return result;
}

#define IS_EXP_SYMBOL(c) (c == 'e' || c == 'E')
#define IS_FLOAT_SUFFIX(c) (c == 'f' || c == 'E')
#define IS_DOUBLE_SUFFIX(c) (c == 'd' || c == 'D')
#define IS_DECIMAL_SUFFIX(c) (c == 'm' || c == 'M')
#define IS_REAL_CHAR(c) IS_DIGIT(c) || (c == '.') || IS_SIGN(c) || IS_EXP_SYMBOL(c) || IS_FLOAT_SUFFIX(c) || IS_DOUBLE_SUFFIX(c) || IS_DECIMAL_SUFFIX(c)

int CheckRealType(char *text)
{
    /**
        Divide text in the following parts:
            -> Number sign (optional);
            -> Integer part of the number;
            -> Fractional part of the number;
            -> Exponent symbol (optional);
            -> Exponent sign (optional);
            -> Exponent number (optional);
            -> Type suffix (optional);

        Return possibilities:
            FLOAT_VAL
            DOUBLE_VAL
            DECIMAL_VAL
    */
    char *letter = text;
    long double sign = 1;
    long double value = 0;
    int chars = 0;
    int offset = 0;
    while (IS_REAL_CHAR(*letter))
    {
        if (IS_SIGN(*letter)) ++offset;
        else if (IS_DIGIT(*letter) || *letter == '.' || IS_EXP_SYMBOL(*letter))
        {
            ++chars;
            ++letter;
        }
        else if (IS_FLOAT_SUFFIX(*letter) || IS_DOUBLE_SUFFIX(*letter) || IS_DECIMAL_SUFFIX(*letter)) break;
    }
    char *number = malloc(chars * sizeof(char));
    number = strncpy(number, text + offset, chars * sizeof(char));
    value = strtold(number, NULL);
    if (value <= FLT_MAX)
    {
        printf("FLOAT_VAL\n");
        return FLOAT_VAL;
    }
    else if (value > FLT_MAX && value <= DBL_MAX)
    {
        printf("DOUBLE_VAL\n");
        return DOUBLE_VAL;
    }
    else
    {
        printf("DECIMAL_VAL\n");
        return DECIMAL_VAL;
    }
}

