#line 2 "src/Scanner/scanner.c"

#line 4 "src/Scanner/scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 134
#define YY_END_OF_BUFFER 135
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[563] =
    {   0,
        0,    0,  135,  134,   15,  134,   14,   25,  134,    4,
        5,   13,   10,   20,   11,   21,   12,  123,  123,  123,
       18,   19,   23,   22,   24,   16,  134,  122,    8,    9,
       17,  122,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,    6,
       26,    7,   27,   31,    0,    0,   36,   42,   37,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       34,   45,   32,   46,   33,    0,  122,  122,  122,    0,
        1,   35,    0,    0,  123,  123,  125,  124,    0,  125,
      124,   40,   30,   28,   47,   29,   41,   44,    0,    3,

        3,    0,  122,   39,    0,   51,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   65,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   78,    0,   80,   84,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   38,   43,  133,    0,
      132,  132,  132,  132,  123,  132,  122,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
      126,  127,  127,   48,   49,    0,    0,    3,    3,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   75,    0,    0,   81,    0,    0,   87,    0,
        0,    0,   91,    0,    0,    0,    0,    0,    0,   98,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  131,    0,    0,  131,  123,  123,  123,    0,  131,
      123,  123,  122,  122,    0,  131,    0,  122,    2,    0,
      129,  128,  129,  128,    0,    0,   52,   53,    0,   55,
       56,   57,    0,    0,    0,    0,    0,    0,    0,    0,
       67,   68,    0,    0,    0,    0,    0,    0,    0,   77,

        0,    0,   85,   86,   88,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  109,    0,  111,    0,  113,    0,    0,
        0,    0,    0,  119,    0,    0,    0,    0,    0,    0,
      123,  123,    0,    0,    0,  131,    0,  131,  122,  122,
        0,  130,    0,   54,    0,   59,   60,    0,    0,    0,
        0,    0,   69,    0,    0,   72,   73,   74,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      100,    0,  102,    0,    0,    0,    0,    0,    0,  110,
        0,  114,    0,    0,    0,    0,    0,  121,    0,    0,

        0,    0,    0,    0,    0,    0,    0,  131,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   66,    0,
       71,    0,    0,    0,    0,   89,    0,    0,   93,    0,
        0,   96,    0,   99,  101,  103,    0,  105,  106,  107,
      108,  112,    0,  116,  117,    0,    0,  131,    0,    0,
      131,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      131,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       58,    0,   62,   63,    0,    0,   76,    0,    0,    0,
        0,    0,   94,    0,    0,    0,    0,  118,    0,    0,

      131,    0,  131,  131,    0,    0,  131,   50,   61,   64,
       70,   79,    0,   83,   90,   92,    0,   97,    0,    0,
      120,    0,    0,    0,    0,    0,    0,    0,  131,    0,
        0,    0,    0,    0,    0,   82,   95,    0,  115,    0,
      131,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  104,    0,  131,    0,    0,    0,    0,    0,    0,
        0,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    3,    4,    5,
        6,    1,    7,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    8,    9,    1,    1,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   22,   22,   22,   22,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,    1,    1,   32,   33,   34,
        1,    1,    1,    1,    1,   35,   36,    1,    1,    1,
        1,    1,    1,    1,   37,    1,    1,   38,    1,   39,
       40,    1,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   53,   54,   55,   56,   57,
       58,   59,    1,   60,   61,   62,   63,   64,   65,   66,
       67,   68,   69,   70,   71,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[74] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[568] =
    {   0,
        0,    0, 1040, 1041, 1012,  996, 1010,   63,   73, 1041,
     1041, 1009,   65, 1041,   66,   75,   68,  135,   78,  105,
     1041, 1041,   76,   77,   80, 1006,  106,  132, 1041, 1041,
     1007,  163,  120,  137,   62,   66,  141,  975,  148,  974,
       34,  103,  159,  983,  165,   71,  168,   77,  979, 1041,
       82, 1041, 1041, 1041, 1020,  156, 1041, 1041, 1041, 1016,
     1015, 1014, 1013, 1012, 1011, 1010,  214, 1009, 1008, 1007,
     1041, 1041, 1041, 1041, 1041,  206,  229,  244,  259,   97,
        0, 1041,  253,  258,  294,  270,  152,  114,  301,  169,
      124,  991, 1041, 1041, 1041, 1041,  990, 1041,  973,  307,

      335,  972,  341, 1041,  953, 1041,  952,  954,  963,  948,
      948,  170,  964,  950,  288,  943,  944,  941,  955,   27,
      947,  935,  942,  939,  936, 1041,  938,  934, 1041,  188,
      930,  939,  940,  944,  929,  942,  929,  125,  943,  202,
      920,  942,  927,  916,  168,  931,  206,  919,  922,  923,
      921,  198,  927,  917,  217,  924, 1041, 1041, 1041,  966,
      321,  340, 1041,  365,    0,  370,  383,  962,  961,  960,
      959,  958,  957,  956,  955,  954,  953,  279,  944,    0,
     1041,  361,  362, 1041, 1041,  951,  919,  389,  411,  949,
      898,  911,  903,  913,  908,  907,  894,  907,  891,  234,

      899,  906,  901,  903,  899,  890,  888,  889,  895,  881,
      893,  896,  891,  880,  882,  888,  881,  884, 1041,  878,
      884,  871, 1041,  870,  885,  864,  865,  871,  878, 1041,
      861,  861,  867,  861,  872,  277,  289,  857,  857,  859,
      868,  867,  852,  856,  861,  867,  852,  847,  861,  863,
      851,  417,  893,  425,  433,  441,  446,  451,    0,  459,
      892,  473,  481,  503,  346,  392,  518,  531, 1041,  861,
      184,  156,  247,  313,  890,  841, 1041, 1041,  846, 1041,
     1041, 1041,  845,  837,  835,  844,  839,  831,  843,  837,
     1041, 1041,  829,  838,  829,  840,  840,  824,  841, 1041,

      832,  823, 1041, 1041, 1041,  836,  837,  820,  823,  834,
      829,  824,  817,  814,  825,  824,  809,  812,  815,  812,
      806,  816,  815, 1041,  795, 1041,  797, 1041,  804,  805,
      803,  791,  787, 1041,  787,  800,  512,  420,  544,  557,
      835,  560,  605,  553,  571,  610,  296,  613,  628,  643,
      815, 1041,  785, 1041,  778, 1041, 1041,  768,  780,  759,
      767,  761, 1041,  761,  748, 1041, 1041, 1041,  758,  755,
      321,  730,  725,  734,  724,  720,  725,  721,  709,  708,
     1041,  716, 1041,  708,  711,  707,  698,  683,  693, 1041,
      694, 1041,  692,  685,  669,  680,  670, 1041,  706,  705,

      703,  701,  698,  697,  695,  691,  693,  623,  689,  687,
      685,  683,  682,  677,  671,  668,  637,  656,  666,  672,
      703,  358,  630,  618,  600,  605,  596,  595, 1041,  604,
     1041,  599,  596,  601,  599, 1041,  572,  574, 1041,  569,
      554, 1041,  558, 1041, 1041, 1041,  557, 1041, 1041, 1041,
     1041, 1041,  557, 1041, 1041,  555,  553, 1041,  669,  741,
      468,  679,  594,  586,  584,  582,  581,  580,  579,  578,
      711,  484,  576,  572,  565,  562,  561,  552,  356,  496,
     1041,  509, 1041, 1041,  492,  476, 1041,  473,  487,  477,
      458,  468, 1041,  465,  432,  443,  449, 1041,  429,  447,

      735,  472,  749, 1041,  757,  747, 1041, 1041, 1041, 1041,
     1041, 1041,  428, 1041, 1041, 1041,  428, 1041,  408,  414,
     1041,  772,  437,  766,  787,  423,  784,  499,  800,  419,
      414,  409,  407,  406,  395, 1041, 1041,  359, 1041,  500,
      815,  508,  382,  378,  371,  369,  343,  324,  816,  306,
      809, 1041,  810, 1041,  532,  299,  292,  264,  262,  249,
      245, 1041,  242,  866,  135,  133,  110
    } ;

static yyconst flex_int16_t yy_def[568] =
    {   0,
      562,    1,  562,  562,  562,  563,  562,  562,  564,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  565,  562,  562,  562,  562,
      566,  562,  565,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,

      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  567,   18,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  566,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,

      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  567,  562,   18,  562,  562,  567,  562,
      256,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,

      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  567,  562,
       18,  562,  565,  565,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,

      562,  562,  562,  562,  562,  562,  565,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,

      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,    0,  562,  562,  562,  562,  562
    } ;

static yyconst flex_uint16_t yy_nxt[1115] =
    {   0,
        4,    4,    4,    4,    4,    4,    4,    5,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,    4,    4,    4,    4,    4,    4,    4,   28,   29,
       30,   31,    4,   32,   33,   34,   35,   36,   37,   38,
        4,   39,    4,    4,   40,    4,   41,   42,   43,   44,
       45,   46,   47,   48,   49,    4,    4,   28,   50,   51,
       52,   53,    4,   58,   61,   62,   63,   64,   65,   66,
       72,  131,   80,   74,   67,  208,   76,   81,  209,   59,
       68,   73,   75,   77,   82,   78,  132,   78,   86,   86,

       86,   92,   93,   94,   95,   79,   96,   97,  157,  115,
      253,  178,   87,   79,   88,   69,   83,   99,   79,  116,
      117,  147,  118,   84,  100,   85,   86,   85,  154,  119,
      148,  120,   90,  180,  155,  168,  101,  149,  179,   87,
       91,   88,   79,  102,  101,   70,   83,  133,  181,  101,
      103,  158,   79,   84,   79,   85,   86,   85,  181,   90,
      160,  134,   79,  107,  159,  135,  136,   91,  181,   87,
       79,   88,   89,  101,  102,   79,  226,  108,  181,  109,
      111,  103,  227,   79,  121,   79,  110,  112,  181,   90,
      352,  113,  122,   79,  114,  123,  126,   91,  124,   79,

       89,   79,  137,  127,  128,  181,   79,  105,  129,  141,
      352,  236,  142,  197,  181,  143,  144,  198,  138,  150,
      352,  139,  151,  106,  152,  164,  145,  237,  153,  146,
       79,  181,   84,  217,  165,   86,   85,  169,  170,  171,
       76,  172,   55,  245,  218,  229,  352,   77,  173,   78,
      230,   78,  174,  175,  176,   76,  554,  239,  246,   79,
      554,  177,   77,  231,   78,  240,   78,   79,  249,   83,
      102,  250,   79,  554,   79,  554,   84,  103,   84,   79,
       84,   79,   79,  352,  169,  170,  171,   79,  172,   79,
       86,   86,   86,  178,  285,  286,   79,   79,  269,  174,

      175,  176,   79,  554,   87,   83,   88,  418,  177,  352,
      554,   79,   84,  419,   85,   86,   85,  555,  187,  182,
      179,  183,  319,  183,   90,  188,   79,  189,   87,  189,
       88,  183,   91,  201,  183,  554,  202,  189,  320,  252,
      321,  252,  203,  252,  183,  189,  187,  352,   90,  183,
      189,  322,  102,  188,  554,  189,   91,  189,  252,  103,
      252,   79,  252,   79,  346,  189,  346,  352,  346,  434,
      479,   79,  479,  189,  189,  269,  254,  435,  189,   79,
      554,  259,  554,  255,   79,  256,  257,  258,  260,  554,
      261,   86,  262,  554,  102,  271,  271,  272,  272,  179,

      187,  263,  189,  264,  552,  264,  507,  188,   79,  189,
      346,  189,  346,   79,  346,  273,  273,  507,  507,  189,
      507,   79,  187,  274,  274,  507,   79,  189,  337,  188,
      507,  189,  189,  189,  542,  252,  339,  252,  252,  252,
      252,  189,  252,  340,  343,  341,  257,  342,  540,  189,
       79,  260,  343,  260,  189,  260,  189,  338,  522,  260,
      539,  262,  343,  262,  523,  538,   86,   86,   86,  260,
      344,  262,   86,  262,  537,  536,  521,  260,  189,  260,
       87,  260,   88,  525,  344,   87,  346,   88,  346,  526,
      346,  260,  345,  262,   86,  262,  520,  519,  518,  263,

       90,  264,  471,  264,  471,   90,  471,   87,   91,   88,
      549,   79,  517,   91,  345,  516,  550,  515,  501,   79,
      501,  263,  501,  264,   79,  264,  541,   90,  541,  347,
      541,  514,  513,   79,  512,   91,  348,  511,  348,  510,
      348,   79,  102,  399,  400,  401,   79,  402,   79,  349,
      529,  350,  529,  350,  529,  339,  509,  508,  403,  404,
      405,   79,  255,  507,  256,  257,  258,  406,  407,   79,
       79,  407,  507,  507,   79,   84,  507,   84,   84,   84,
       85,   86,   85,  507,  409,  410,  411,  507,  412,  504,
      504,  505,  504,  504,   87,  504,   88,  505,   79,  413,

      414,  415,  399,  400,  401,  504,  402,  499,  416,  498,
      497,  496,  495,  190,   90,  494,  493,  403,  404,  405,
      492,  417,   91,  408,  420,  408,  406,  408,  346,  491,
      346,  348,  346,  348,  460,  348,  409,  410,  411,  421,
      412,  252,  490,  252,  489,  252,  349,  488,  350,  487,
      350,  413,  414,  415,  421,  486,  485,  484,   79,  483,
      416,  349,  482,  350,  481,  350,   79,  418,  463,  464,
      465,   79,  466,   79,  471,  480,  471,  472,  471,  461,
      500,   79,  461,  467,  468,  469,   79,  501,  462,  501,
      502,  501,  470,  461,  461,   79,  461,  503,  462,  503,

      461,  503,  458,  473,  464,  474,  458,  475,  459,  458,
       79,  408,  458,  408,  458,  408,  459,  458,  476,  468,
      477,  457,  506,  456,  169,  170,  171,  478,  172,  471,
      455,  471,  454,  471,  463,  464,  465,  453,  466,  174,
      175,  176,  452,  451,  450,  190,  524,  449,  177,  467,
      468,  469,  448,  501,  447,  501,  446,  501,  470,  346,
      527,  346,  445,  346,  444,  443,  442,  503,  528,  503,
      441,  503,  399,  400,  401,  529,  402,  529,  530,  529,
      531,  440,  532,  522,  439,  438,  437,  403,  404,  405,
      501,  436,  501,  533,  501,  534,  406,  399,  525,  401,

      433,  402,  535,  432,  431,  541,  430,  541,  429,  541,
      428,  551,  403,  427,  405,  543,  464,  544,  529,  545,
      529,  406,  529,  426,  425,  424,  553,  549,  423,  422,
      546,  468,  547,  541,  529,  541,  529,  541,  529,  548,
      463,  556,  465,  557,  466,  558,  407,  398,  397,  396,
      395,  394,  393,  392,  391,  467,  559,  469,  560,  390,
      389,  388,  387,  386,  470,  561,   60,   60,  385,  384,
      383,  382,  381,  380,  379,  378,  377,  376,  375,  374,
      373,  372,  371,  370,  369,  368,  367,  366,  365,  364,
      363,  362,  361,  360,  359,  358,  357,  356,  355,  354,

      353,  189,  351,  344,  338,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  325,  324,  323,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  292,  291,  290,  289,  288,
      287,  284,  283,  282,  281,  280,  279,  278,  277,  276,
       79,  275,  101,  270,  266,  266,  267,  266,  268,  266,
      266,  267,  266,  265,  159,  251,  248,  247,  244,  243,
      242,  241,  238,  235,  234,  233,  232,  228,  225,  224,
      223,  222,  221,  220,  219,  216,  215,  214,  213,  212,

      211,  210,  207,  206,  205,  204,  200,  199,  196,  195,
      194,  193,  192,  191,  190,  186,  185,  184,  162,  167,
      166,  162,  162,  163,  162,  162,  162,  161,  159,  156,
      140,  130,  125,  104,   98,   71,   57,   56,   54,  562,
        3,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,

      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562
    } ;

static yyconst flex_int16_t yy_chk[1115] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    8,    9,    9,    9,    9,    9,    9,
       13,   41,   17,   15,    9,  120,   16,   17,  120,    8,
        9,   13,   15,   16,   17,   16,   41,   16,   19,   19,

       19,   23,   23,   24,   24,   16,   25,   25,   51,   35,
      567,   80,   19,   16,   19,    9,   20,   27,   16,   35,
       36,   46,   36,   20,   27,   20,   20,   20,   48,   36,
       46,   36,   19,  566,   48,  565,   27,   46,   80,   20,
       19,   20,   16,   28,   27,    9,   18,   42,   88,   27,
       28,   51,   28,   18,   28,   18,   18,   18,   91,   20,
       56,   42,   28,   33,   56,   42,   42,   20,   88,   18,
       28,   18,   18,   27,   32,   28,  138,   33,   91,   33,
       34,   32,  138,   32,   37,   32,   33,   34,   87,   18,
      272,   34,   37,   32,   34,   37,   39,   18,   37,   28,

       18,   32,   43,   39,   39,   90,   32,   32,   39,   45,
      272,  145,   45,  112,   87,   45,   45,  112,   43,   47,
      271,   43,   47,   32,   47,   67,   45,  145,   47,   45,
       32,   90,   67,  130,   67,   67,   67,   76,   76,   76,
       77,   76,  563,  152,  130,  140,  271,   77,   76,   77,
      140,   77,   76,   76,   76,   78,  561,  147,  152,   77,
      560,   76,   78,  140,   78,  147,   78,   77,  155,   84,
       79,  155,   77,  559,   78,  558,   84,   79,   84,   79,
       84,   79,   78,  273,   83,   83,   83,   78,   83,   79,
       86,   86,   86,  178,  200,  200,   77,   79,  178,   83,

       83,   83,   79,  557,   86,   85,   86,  347,   83,  273,
      556,   78,   85,  347,   85,   85,   85,  550,  100,   89,
      178,   89,  236,   89,   86,  100,   79,  100,   85,  100,
       85,   89,   86,  115,   89,  548,  115,  100,  236,  161,
      237,  161,  115,  161,   89,  100,  101,  274,   85,   89,
      100,  237,  103,  101,  547,  101,   85,  101,  162,  103,
      162,  103,  162,  103,  265,  101,  265,  274,  265,  371,
      479,  103,  422,  101,  100,  479,  164,  371,  101,  103,
      546,  166,  545,  164,  103,  164,  164,  164,  166,  544,
      166,  166,  166,  543,  167,  182,  183,  182,  183,  422,

      188,  167,  101,  167,  538,  167,  535,  188,  103,  188,
      266,  188,  266,  167,  266,  182,  183,  534,  533,  188,
      532,  167,  189,  182,  183,  531,  167,  188,  252,  189,
      530,  189,  188,  189,  526,  252,  254,  252,  338,  252,
      338,  189,  338,  254,  255,  254,  254,  254,  523,  189,
      167,  255,  256,  255,  189,  255,  188,  257,  500,  256,
      520,  256,  258,  256,  500,  519,  257,  257,  257,  258,
      260,  258,  258,  258,  517,  513,  499,  260,  189,  260,
      257,  260,  257,  502,  262,  258,  461,  258,  461,  502,
      461,  262,  263,  262,  262,  262,  497,  496,  495,  263,

      257,  263,  472,  263,  472,  258,  472,  262,  257,  262,
      528,  263,  494,  258,  264,  492,  528,  491,  540,  263,
      540,  264,  540,  264,  263,  264,  542,  262,  542,  267,
      542,  490,  489,  264,  488,  262,  267,  486,  267,  485,
      267,  264,  268,  337,  337,  337,  264,  337,  263,  268,
      555,  268,  555,  268,  555,  339,  482,  480,  337,  337,
      337,  268,  339,  478,  339,  339,  339,  337,  340,  268,
      264,  342,  477,  476,  268,  340,  475,  340,  342,  340,
      342,  342,  342,  474,  344,  344,  344,  473,  344,  470,
      469,  468,  467,  466,  342,  465,  342,  464,  268,  344,

      344,  344,  345,  345,  345,  463,  345,  457,  344,  456,
      453,  447,  443,  345,  342,  441,  440,  345,  345,  345,
      438,  346,  342,  343,  348,  343,  345,  343,  346,  437,
      346,  348,  346,  348,  408,  348,  343,  343,  343,  349,
      343,  408,  435,  408,  434,  408,  349,  433,  349,  432,
      349,  343,  343,  343,  350,  430,  428,  427,  349,  426,
      343,  350,  425,  350,  424,  350,  349,  418,  417,  417,
      417,  349,  417,  350,  418,  423,  418,  419,  418,  416,
      459,  350,  415,  417,  417,  417,  350,  459,  414,  459,
      462,  459,  417,  413,  412,  349,  411,  462,  410,  462,

      409,  462,  406,  420,  420,  420,  405,  420,  404,  403,
      350,  407,  402,  407,  401,  407,  400,  399,  420,  420,
      420,  397,  471,  396,  407,  407,  407,  420,  407,  471,
      395,  471,  394,  471,  421,  421,  421,  393,  421,  407,
      407,  407,  391,  389,  388,  421,  501,  387,  407,  421,
      421,  421,  386,  501,  385,  501,  384,  501,  421,  460,
      503,  460,  382,  460,  380,  379,  378,  503,  505,  503,
      377,  503,  460,  460,  460,  505,  460,  505,  506,  505,
      506,  376,  506,  522,  375,  374,  373,  460,  460,  460,
      522,  372,  522,  506,  522,  506,  460,  524,  525,  524,

      370,  524,  506,  369,  365,  525,  364,  525,  362,  525,
      361,  529,  524,  360,  524,  527,  527,  527,  529,  527,
      529,  524,  529,  359,  358,  355,  541,  549,  353,  351,
      527,  527,  527,  541,  549,  541,  549,  541,  549,  527,
      551,  553,  551,  553,  551,  553,  341,  336,  335,  333,
      332,  331,  330,  329,  327,  551,  553,  551,  553,  325,
      323,  322,  321,  320,  551,  553,  564,  564,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  302,  301,  299,  298,  297,  296,  295,  294,
      293,  290,  289,  288,  287,  286,  285,  284,  283,  279,

      276,  275,  270,  261,  253,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  239,  238,  235,
      234,  233,  232,  231,  229,  228,  227,  226,  225,  224,
      222,  221,  220,  218,  217,  216,  215,  214,  213,  212,
      211,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      201,  199,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  187,  186,  179,  177,  176,  175,  174,  173,  172,
      171,  170,  169,  168,  160,  156,  154,  153,  151,  150,
      149,  148,  146,  144,  143,  142,  141,  139,  137,  136,
      135,  134,  133,  132,  131,  128,  127,  125,  124,  123,

      122,  121,  119,  118,  117,  116,  114,  113,  111,  110,
      109,  108,  107,  105,  102,   99,   97,   92,   70,   69,
       68,   66,   65,   64,   63,   62,   61,   60,   55,   49,
       44,   40,   38,   31,   26,   12,    7,    6,    5,    3,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,

      562,  562,  562,  562,  562,  562,  562,  562,  562,  562,
      562,  562,  562,  562
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/Scanner/c-sharp.l"
/* Scanner for a C# 6.0 compiler generated with Flex */
#line 4 "src/Scanner/c-sharp.l"

#include <stdlib.h>

#define INT_MAX_VALUE   2147483647
#define UINT_MAX_VALUE  4294967295
#define LONG_MAX_VALUE  9223372036854775807

int CheckIntType(long long value, char *suffix);
long long TreatIntString(char *text);
long long TreatHexString(char *text);
int CheckRealType(char *text);

/* character_literal '\''{character}'\''

character .|{simple_escape_sequence}|{hexadecimal_escape_sequence}

simple_escape_sequence '\\\''|'\\"'|'\\\\'|'\\0'|'\\a'|'\\b'|'\\f'|'\\n'|'\\r'|'\\t'|'\\v'

hexadecimal_escape_sequence "\\x"([0..9]|[a..f]|[A..F])([0..9]|[a..f]|[A..F])?([0..9]|[a..f]|[A..F])?([0..9]|[a..f]|[A..F])? */
#line 921 "src/Scanner/scanner.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 40 "src/Scanner/c-sharp.l"


#line 1142 "src/Scanner/scanner.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 563 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1041 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 42 "src/Scanner/c-sharp.l"
{ /* singleline comments are ignored*/ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 43 "src/Scanner/c-sharp.l"
{ /* multiline comments are ignored */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 45 "src/Scanner/c-sharp.l"
{ return IDENTIFIER; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 47 "src/Scanner/c-sharp.l"
{ return START_PAR; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 48 "src/Scanner/c-sharp.l"
{ return END_PAR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 49 "src/Scanner/c-sharp.l"
{ return START_CURLY; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 50 "src/Scanner/c-sharp.l"
{ return END_CURLY; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 51 "src/Scanner/c-sharp.l"
{ return START_BRCKT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 52 "src/Scanner/c-sharp.l"
{ return END_BRCKT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 53 "src/Scanner/c-sharp.l"
{ return ADD; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 54 "src/Scanner/c-sharp.l"
{ return SUB; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 55 "src/Scanner/c-sharp.l"
{ return DIV; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 56 "src/Scanner/c-sharp.l"
{ return MUL; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 57 "src/Scanner/c-sharp.l"
{ return MOD; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 58 "src/Scanner/c-sharp.l"
{ return NOT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 59 "src/Scanner/c-sharp.l"
{ return QMARK; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 60 "src/Scanner/c-sharp.l"
{ return CIRCUMFLEX; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 61 "src/Scanner/c-sharp.l"
{ return COLON; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 62 "src/Scanner/c-sharp.l"
{ return SEMI; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 63 "src/Scanner/c-sharp.l"
{ return COMMA; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 64 "src/Scanner/c-sharp.l"
{ return DOT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 65 "src/Scanner/c-sharp.l"
{ return ASSIGN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 66 "src/Scanner/c-sharp.l"
{ return LESS_THEN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 67 "src/Scanner/c-sharp.l"
{ return GREATER_THEN; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 68 "src/Scanner/c-sharp.l"
{ return BIT_AND; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 69 "src/Scanner/c-sharp.l"
{ return BIT_OR; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 70 "src/Scanner/c-sharp.l"
{ return BIT_NOT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 71 "src/Scanner/c-sharp.l"
{ return EQ; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 72 "src/Scanner/c-sharp.l"
{ return GEQ; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 73 "src/Scanner/c-sharp.l"
{ return LEQ; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 74 "src/Scanner/c-sharp.l"
{ return NOT_EQ; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 75 "src/Scanner/c-sharp.l"
{ return ADD_ASSIGN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 76 "src/Scanner/c-sharp.l"
{ return SUB_ASSIGN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 77 "src/Scanner/c-sharp.l"
{ return MUL_ASSIGN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 78 "src/Scanner/c-sharp.l"
{ return DIV_ASSIGN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 79 "src/Scanner/c-sharp.l"
{ return MOD_ASSIGN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 80 "src/Scanner/c-sharp.l"
{ return BIT_AND_ASSIGN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 81 "src/Scanner/c-sharp.l"
{ return BIT_OR_ASSIGN; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 82 "src/Scanner/c-sharp.l"
{ return CIRCUMFLEX_ASSIGN; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 83 "src/Scanner/c-sharp.l"
{ return LEFT_SHIFT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 84 "src/Scanner/c-sharp.l"
{ return RIGHT_SHIFT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 85 "src/Scanner/c-sharp.l"
{ return AND; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 86 "src/Scanner/c-sharp.l"
{ return OR; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 87 "src/Scanner/c-sharp.l"
{ return DOUBLE_QMARK; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 88 "src/Scanner/c-sharp.l"
{ return INCREMENT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 89 "src/Scanner/c-sharp.l"
{ return DECREMENT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 90 "src/Scanner/c-sharp.l"
{ return LAMBDA; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 91 "src/Scanner/c-sharp.l"
{ return LEFT_SHIFT_ASSIGN; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 92 "src/Scanner/c-sharp.l"
{ return RIGHT_SHIFT_ASSIGN; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 93 "src/Scanner/c-sharp.l"
{ return ABSTRACT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 94 "src/Scanner/c-sharp.l"
{ return AS; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 95 "src/Scanner/c-sharp.l"
{ return BASE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 96 "src/Scanner/c-sharp.l"
{ return BOOL_TYPE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 97 "src/Scanner/c-sharp.l"
{ return BREAK; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 98 "src/Scanner/c-sharp.l"
{ return BYTE_TYPE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 99 "src/Scanner/c-sharp.l"
{ return CASE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 100 "src/Scanner/c-sharp.l"
{ return CHAR_TYPE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 101 "src/Scanner/c-sharp.l"
{ return CHECKED; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 102 "src/Scanner/c-sharp.l"
{ return CLASS; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 103 "src/Scanner/c-sharp.l"
{ return CONST; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 104 "src/Scanner/c-sharp.l"
{ return CONTINUE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 105 "src/Scanner/c-sharp.l"
{ return DECIMAL_TYPE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 106 "src/Scanner/c-sharp.l"
{ return DEFAULT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 107 "src/Scanner/c-sharp.l"
{ return DELEGATE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 108 "src/Scanner/c-sharp.l"
{ return DO; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 109 "src/Scanner/c-sharp.l"
{ return DOUBLE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 110 "src/Scanner/c-sharp.l"
{ return ELSE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 111 "src/Scanner/c-sharp.l"
{ return ENUM; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 112 "src/Scanner/c-sharp.l"
{ return EVENT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 113 "src/Scanner/c-sharp.l"
{ return EXPLICIT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 114 "src/Scanner/c-sharp.l"
{ return EXTERN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 115 "src/Scanner/c-sharp.l"
{ return FALSE_VAL; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 116 "src/Scanner/c-sharp.l"
{ return FIXED; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 117 "src/Scanner/c-sharp.l"
{ return FLOAT_TYPE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 118 "src/Scanner/c-sharp.l"
{ return FOR; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 119 "src/Scanner/c-sharp.l"
{ return FOREACH; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 120 "src/Scanner/c-sharp.l"
{ return GOTO; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 121 "src/Scanner/c-sharp.l"
{ return IF; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 122 "src/Scanner/c-sharp.l"
{ return IMPLICIT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 123 "src/Scanner/c-sharp.l"
{ return IN; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 124 "src/Scanner/c-sharp.l"
{ return INT_TYPE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 125 "src/Scanner/c-sharp.l"
{ return INTERFACE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 126 "src/Scanner/c-sharp.l"
{ return INTERNAL; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 127 "src/Scanner/c-sharp.l"
{ return IS; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 128 "src/Scanner/c-sharp.l"
{ return LOCK; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 129 "src/Scanner/c-sharp.l"
{ return LONG_TYPE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 130 "src/Scanner/c-sharp.l"
{ return NEW; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 131 "src/Scanner/c-sharp.l"
{ return NULL_VALUE; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 132 "src/Scanner/c-sharp.l"
{ return OBJECT; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 133 "src/Scanner/c-sharp.l"
{ return OPERATOR; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 134 "src/Scanner/c-sharp.l"
{ return OUT; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 135 "src/Scanner/c-sharp.l"
{ return OVERRIDE; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 136 "src/Scanner/c-sharp.l"
{ return PARAMS; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 137 "src/Scanner/c-sharp.l"
{ return PRIVATE; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 138 "src/Scanner/c-sharp.l"
{ return PROTECTED; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 139 "src/Scanner/c-sharp.l"
{ return PUBLIC; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 140 "src/Scanner/c-sharp.l"
{ return READONLY; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 141 "src/Scanner/c-sharp.l"
{ return REF; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 142 "src/Scanner/c-sharp.l"
{ return RETURN; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 143 "src/Scanner/c-sharp.l"
{ return SBYTE_TYPE; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 144 "src/Scanner/c-sharp.l"
{ return SEALED; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 145 "src/Scanner/c-sharp.l"
{ return SHORT_TYPE; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 146 "src/Scanner/c-sharp.l"
{ return SIZEOF; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 147 "src/Scanner/c-sharp.l"
{ return STACKALLOC; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 148 "src/Scanner/c-sharp.l"
{ return STATIC; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 149 "src/Scanner/c-sharp.l"
{ return STRING_TYPE; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 150 "src/Scanner/c-sharp.l"
{ return STRUCT; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 151 "src/Scanner/c-sharp.l"
{ return SWITCH; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 152 "src/Scanner/c-sharp.l"
{ return THIS; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 153 "src/Scanner/c-sharp.l"
{ return THROW; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 154 "src/Scanner/c-sharp.l"
{ return TRUE_VAL; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 155 "src/Scanner/c-sharp.l"
{ return TYPEOF; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 156 "src/Scanner/c-sharp.l"
{ return UINT_TYPE; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 157 "src/Scanner/c-sharp.l"
{ return ULONG_TYPE; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 158 "src/Scanner/c-sharp.l"
{ return UNCHECKED; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 159 "src/Scanner/c-sharp.l"
{ return UNSAFE; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 160 "src/Scanner/c-sharp.l"
{ return USHORT_TYPE; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 161 "src/Scanner/c-sharp.l"
{ return VIRTUAL; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 162 "src/Scanner/c-sharp.l"
{ return VOID; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 163 "src/Scanner/c-sharp.l"
{ return VOLATILE; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 164 "src/Scanner/c-sharp.l"
{ return WHILE; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 166 "src/Scanner/c-sharp.l"
{ return IDENTIFIER; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 168 "src/Scanner/c-sharp.l"
{ long long value = atoll(yytext); return CheckIntType(value, NULL); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 169 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatIntString(yytext)); return CheckIntType(value, "U"); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 170 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatIntString(yytext)); return CheckIntType(value, "L"); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 171 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatIntString(yytext)); return CheckIntType(value, "UL"); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 173 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatHexString(yytext)); return CheckIntType(value, NULL); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 174 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatHexString(yytext)); return CheckIntType(value, "U"); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 175 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatHexString(yytext)); return CheckIntType(value, "L"); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 176 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatHexString(yytext)); return CheckIntType(value, "UL"); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 178 "src/Scanner/c-sharp.l"
{ return CheckRealType(yytext); }
	YY_BREAK
case 132:
/* rule 132 can match eol */
YY_RULE_SETUP
#line 180 "src/Scanner/c-sharp.l"
{ return CHAR_VAL; }
	YY_BREAK
case 133:
/* rule 133 can match eol */
YY_RULE_SETUP
#line 182 "src/Scanner/c-sharp.l"
{ return STRING_VAL; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 184 "src/Scanner/c-sharp.l"
ECHO;
	YY_BREAK
#line 1871 "src/Scanner/scanner.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 73);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 563 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 73;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 563 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 562);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 184 "src/Scanner/c-sharp.l"



%{

int CheckIntType(long long value, char *suffix)
{
    value = llabs(value);

    // If there's no suffix telling which type it is:
    if (suffix == NULL)
    {
        // Comparing the value with the maximum size of each type to define the type that must be returned:
        if (value <= INT_MAX_VALUE) return INT_VALUE;
        else if (value <= UINT_MAX_VALUE) return UINT_VALUE;
        else if (value <= LONG_MAX_VALUE) return LONG_VALUE;
        else if (value <= ULONG_MAX_VALUE) return ULONG_VALUE;
    }
    else if (strcmp(suffix, "U") == 0)
        goto start_from_unsigned;
    else if (strcmp(suffix, "L") == 0)
        goto start_from_long;
    else if (strcmp(suffix, "Ul") == 0)
        goto start_from_unsigned;

    start_from_unsigned:
    if (value <= UINT_MAX_VALUE) return UINT_VALUE;
    
    start_from_long:
    if (value > UINT_MAX_VALUE) return LONG_VALUE;
    
    start_from_ulong:
    if (value > LONG_MAX_VALUE) return ULONG_VALUE;

    return -1;
}

#define IS_SIGN(c) (c == '+' || c == '-')
#define IS_DIGIT(c) ('0' <= c && c <= '9')
#define IS_HIGHCASE_HEX(c) ('A' <= c && c <= 'F')
#define IS_LOWCASE_HEX(c) ('a' <= c && c <= 'f')
#define CONVERT_HIGHCASE_HEX(c) (c - 55)
#define CONVERT_LOWCASE_HEX(c) (c - 87)

long long TreatIntString(char *text)
{
    char *letterPtr = text;
    int digits = 0;
    while (IS_DIGIT(*letterPtr) || IS_SIGN(*letterPtr))
    {
        ++digits;
        ++letterPtr;
    }
    char *number = malloc(digits * sizeof(char));
    number = strcpy(number, text, digits * sizeof(char));
    long long result = atoll(number);
    free(number);
    return result;
}

long long TreatHexString(char *text)
{
    char *letter = text;
    int digits = 0;
    long long result = 0;
    while (IS_DIGIT(*letter) || IS_HIGHCASE_HEX(*letter) || IS_LOWCASE_HEX(*letter) || *letter == 'x' || *letter == 'X' || IS_SIGN(*letter))
    {
        ++digits;
        ++letter;
    }
    char *number = malloc(digits * sizeof(char));
    number = strcpy(number, text, digits * sizeof(char));
    result = (long long)strtol(number, 0);
    return result;
}

#define IS_EXP_SYMBOL(c) (c == 'e' || c == 'E')
#define IS_FLOAT_SUFFIX(c) (c == 'f' || c == 'E')
#define IS_DOUBLE_SUFFIX(c) (c == 'd' || c == 'D')
#define IS_DECIMAL_SUFFIX(c) (c == 'm' || c == 'M')
#define IS_REAL_CHAR(c) IS_DIGIT(c) || (c == '.') || IS_SIGN(c) || IS_EXP_SYMBOL(c) || IS_FLOAT_SUFFIX(c) || IS_DOUBLE_SUFFIX(c) || IS_DECIMAL_SUFFIX(c)

int CheckRealType(char *text)
{
    /**
        Divide text in the following parts:
            -> Number sign (optional);
            -> Integer part of the number;
            -> Fractional part of the number;
            -> Exponent symbol (optional);
            -> Exponent sign (optional);
            -> Exponent number (optional);
            -> Type suffix (optional);

        Return possibilities:
            FLOAT_VAL
            DOUBLE_VAL
            DECIMAL_VAL
    */
    char *letter = text;
    long double sign = 1;
    long double value = 0;
    int chars = 0;
    int offset = 0;
    while (IS_REAL_CHAR(*letter))
    {
        if (IS_SIGN(*letter)) ++offset;
        else if (IS_DIGIT(*letter) || *letter == '.' || IS_EXP_SYMBOL(*letter))
        {
            ++chars;
            ++letter;
        }
        else if (IS_FLOAT_SUFFIX(*letter) || IS_DOUBLE_SUFFIX(*letter) || IS_DECIMAL_SUFFIX(*letter)) break;
    }
    char *number = malloc(chars * sizeof(char));
    number = strcpy(number, text + offset, chars * sizeof(char));
    value = strtold(number);
    if (value <= FLT_MAX) return FLOAT_VAL;
    else if (value > FLT_MAX && value <= DBL_VAL) return DOUBLE_VAL;
    else return DECIMAL_VAL;
}

%}

