#line 2 "src/Scanner/scanner.c"

#line 4 "src/Scanner/scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 132
#define YY_END_OF_BUFFER 133
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[526] =
    {   0,
        0,    0,  133,  132,    1,   15,  132,   14,   25,  132,
        4,    5,   13,   10,   20,   11,   21,   12,  120,  120,
       18,   19,   23,   22,   24,   16,  119,    8,  132,    9,
       17,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,    6,
       26,    7,   27,   31,    0,  131,   36,   42,   37,    0,
        0,    0,    0,    0,   34,   45,   32,   46,   33,    0,
        2,   35,    0,  120,  122,  121,    0,  122,  121,   40,
       30,   28,   47,   29,   41,   44,    0,  119,  130,   39,
      119,   51,  119,  119,  119,  119,  119,  119,  119,  119,

      119,   65,  119,  119,  119,  119,  119,  119,  119,  119,
      119,   78,  119,   80,   84,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,   38,   43,  129,  129,  120,  129,    0,    0,
        0,    0,    0,    0,    0,  119,    0,    0,    2,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  123,  124,
       48,   49,    0,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,   75,  119,  119,   81,  119,

       86,  119,  119,  119,   90,  119,  119,  119,  119,  119,
      119,   97,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  128,    0,    0,  120,  120,    0,  120,  120,  129,
      119,    3,    0,    0,  128,    0,  126,  125,  126,  125,
      119,   52,   53,  119,   55,   56,   57,  119,  119,  119,
      119,  119,  119,  119,  119,   67,   68,  119,  119,  119,
      119,  119,  119,  119,   77,  119,  119,   85,   87,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  108,  109,  119,

      111,  119,  119,  119,  119,  119,  117,  119,    0,    0,
        0,  120,  120,    0,    0,    0,    0,  128,    0,  128,
      127,  119,   54,  119,   59,   60,  119,  119,  119,  119,
      119,   69,  119,  119,   72,   73,   74,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,   99,
      119,  101,  119,  119,  119,  119,  119,  119,  119,  112,
      119,  119,  119,  119,  118,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  128,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  119,  119,
      119,  119,  119,  119,   66,  119,   71,  119,  119,  119,

      119,   88,  119,  119,   92,  119,  119,   95,  119,   98,
      100,  102,  119,  104,  105,  106,  107,  110,  119,  114,
      115,  119,  128,    0,    0,  128,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  128,    0,    0,    0,
        0,    0,    0,    0,  119,   58,  119,   62,   63,  119,
      119,   76,  119,  119,  119,  119,  119,   93,  119,  119,
      119,  119,  116,    0,  128,    0,  128,  128,    0,    0,
      128,   50,   61,   64,   70,   79,  119,   83,   89,   91,
      119,   96,  119,  119,    0,    0,    0,    0,    0,    0,
        0,  128,    0,    0,    0,    0,    0,    0,   82,   94,

      119,  113,    0,  128,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  103,    0,  128,    0,    0,    0,
        0,    0,    0,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   32,   30,   30,   30,
       30,   30,   30,   30,   33,   30,   30,   34,   30,   30,
       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    4,    1,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    3,
        3,    3,    3,    3,    1,    1,    1,    1,    1,    4,
        4,    4,    4,    4,    4,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[533] =
    {   0,
        0,    0, 1109, 1110, 1110, 1085, 1101, 1083,   62,   62,
     1110, 1110, 1082,   59, 1110,   58, 1110,   63,   69,   74,
     1110, 1110,   67,   71,   73, 1079, 1094, 1110, 1049, 1110,
     1078,   65,   82,   70,   99,  103,   90,   95,  105,  106,
       67,  107,  119,   75,  133,  126,  136,  117,  100, 1110,
      108, 1110, 1110, 1110, 1094, 1093, 1110, 1110, 1110, 1089,
      179, 1088,  160, 1087, 1110, 1110, 1110, 1110, 1110,  158,
        0, 1110,  179,  196,   80,  121,    0,  122,  179, 1072,
     1110, 1110, 1110, 1110, 1071, 1110, 1054, 1083, 1110, 1110,
      128, 1082,  176,  182,  184,  190,  193,  195,  200,  207,

      203,  209,  194,  211,  217,  223,  216,  224,  229,  228,
      232, 1081,  233,  234, 1080,  237,  235,  241,  246,  250,
      244,  254,  248,  253,  255,  259,  249,  266,  256,  257,
      268,  261,  263,  264,  265,  270,  267,  272,  280,  271,
      291,  293, 1110, 1110,  297,  317,  324,  328, 1079, 1078,
     1077, 1076, 1075, 1074, 1073,  331,  300, 1064,    0, 1071,
     1070, 1069, 1068, 1067, 1066, 1065, 1064, 1063, 1110,  301,
     1110, 1110, 1062,  310,  320,  322,  336,  335,  339,  342,
      109,  344,  345,  347,  350,  353,  351,  354,  356,  357,
      358,  361,  359,  362,  371,  363,  365,  369,  368,  372,

     1061,  373,  377,  376, 1060,  379,  382,  380,  384,  387,
      385, 1059,  391,  404,  405,  392,  406,  416,  407,  414,
      418,  417,  420,  421,  425,  422,  426,  423,  428,  431,
      430,  435, 1058,  453,  470,  474,    0,  477,  481, 1110,
      497, 1110, 1028,  427,  429,  500,  424,  434,  437,  451,
      482, 1056, 1055,  485, 1054, 1053, 1052,  504,  459,  489,
      511,  513,  514,  515,  517, 1051, 1050,  518,  522,  527,
      520,  529,  533,  535, 1049,  534,  536, 1048, 1047,  537,
      538,  540,  542,  541,  543,  547,  544,  546,  557,  558,
      548,  551,  549,  560,  553,  554,  562, 1046, 1045,  564,

     1044,  567,  571,  574,  576,  577, 1043,  579,  582,  441,
      603,  611,  622,  620,  648,  658, 1039,  641,  642,  649,
     1110,  626, 1041,  580, 1040, 1039,  608,  669,  581,  672,
      645, 1038,  627,  661, 1037, 1036, 1035,  637,  674,  675,
      647,  679,  685,  686,  687,  689,  690,  695,  696, 1034,
      698, 1033,  702,  699,  708,  582,  704,  706,  709, 1032,
      710,  712,  713,  715, 1031, 1030, 1029, 1028, 1027, 1026,
     1025, 1024, 1023,  739,  716, 1022, 1021, 1020, 1019, 1018,
     1017, 1016, 1015,  724,  749,  742, 1014,  768,  717,  721,
      714,  718,  720,  728, 1013,  756, 1012,  733,  761,  766,

      776, 1011,  734,  764, 1010,  777,  731, 1009,  780, 1008,
     1007, 1006,  789, 1005, 1004, 1003, 1002, 1001,  793, 1000,
      999,  790, 1110,  796,  805,  799,  810,  791,  998,  997,
      996,  995,  994,  993,  992,  991,  817,  820,  990,  989,
      988,  987,  986,  985,  801,  984,  818,  983,  980,  821,
      813,  976,  816,  835,  833,  836,  837,  972,  838,  842,
      843,  844,  966,  846,  845,  858,  850, 1110,  861,  858,
     1110,  962,  959,  958,  957,  955,  847,  954,  952,  950,
      849,  948,  857,  862,  877,  946,  870,  889,  945,  889,
      874,  905,  944,  943,  942,  941,  939,  938,  934,  928,

      867,  916,  901,  917,  909,  903,  895,  891,  869,  865,
      736,  920,  634,  913,  607,  917, 1110,  912,  591,  443,
      433,  277,  275,  152, 1110,  969,  973,  975,  979,  983,
      129,  987
    } ;

static const flex_int16_t yy_def[533] =
    {   0,
      525,    1,  525,  525,  525,  525,  526,  525,  525,  527,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  528,  525,  525,  525,
      525,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  525,
      525,  525,  525,  525,  526,  526,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      529,  525,  530,  525,  525,  525,  531,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  528,  525,  525,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,

      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  525,  525,  525,  532,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  528,  525,  525,  529,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,

      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  525,  525,  532,  525,  525,  532,  525,  525,  525,
      528,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,

      528,  528,  528,  528,  528,  528,  528,  528,  525,  525,
      532,  525,  525,  530,  530,  525,  525,  525,  525,  525,
      525,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  528,  525,  525,  525,  525,  525,
      525,  525,  525,  530,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  528,  528,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,

      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  525,  525,  525,  525,  525,  525,  525,
      525,  528,  528,  528,  528,  528,  528,  528,  528,  528,
      528,  528,  528,  528,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  528,  528,

      528,  528,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  528,  525,  525,  525,  525,  525,
      525,  525,  525,  525,    0,  525,  525,  525,  525,  525,
      525,  525
    } ;

static const flex_int16_t yy_nxt[1180] =
    {   0,
        4,    5,    5,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   28,   29,   30,   31,    4,   32,
       33,   34,   35,   36,   37,   38,   27,   39,   27,   27,
       40,   27,   41,   42,   43,   27,   44,   45,   46,   47,
       48,   49,   27,   27,   27,   50,   51,   52,   53,   58,
       61,   66,   68,   87,   70,   87,   62,   73,   87,   71,
       69,   67,   73,   87,   59,   72,   74,   74,   80,   81,
       87,   74,   74,   82,   83,   84,   85,   63,   87,   75,

       64,   76,   77,   87,   75,   91,   76,   87,   87,   97,
      117,   87,  169,   87,   87,   87,   98,   87,  126,   78,
       99,   93,   92,  100,   78,   87,  118,   87,   79,  107,
      143,   77,  170,   79,   87,   94,   87,  108,   95,  169,
      109,   87,  101,  110,   87,   96,  142,  119,  111,  112,
      258,  169,  102,  103,  169,  104,  113,  114,  123,  116,
      517,  120,  115,  105,  140,  106,  121,  122,  145,  157,
      141,  169,  133,  127,  144,  124,  128,  149,  125,  129,
      130,  169,  134,  136,   87,  174,  137,  146,  138,  135,
       87,  131,   87,  139,  132,  158,  147,   74,   87,  150,

      151,   87,   87,   87,   73,  161,  162,  163,   87,  169,
      164,   87,  152,   74,   74,   87,  153,   87,  154,   87,
      155,  165,  166,  167,   87,   87,   75,  177,   76,  169,
      168,   87,   87,  175,  180,  176,   87,   87,  181,  182,
       87,   87,   87,   87,  184,   87,   78,  185,  178,   87,
      179,  188,   87,  186,   87,   79,   87,   87,   87,  183,
      190,   87,   87,   87,   87,   87,  193,   87,  187,   87,
      189,   87,   87,   87,   87,   87,   87,  191,   87,   87,
       87,  192,  195,  517,  196,  517,  194,  198,   87,  200,
      197,  202,  199,  204,  203,  210,  201,  206,  211,   87,

      208,   87,  205,  212,  207,  215,  209,  218,  220,  216,
      221,  157,  214,  226,  232,  232,  242,  213,   87,  223,
      225,  217,  224,  222,  219,  234,  228,  229,   87,  227,
       87,  247,   73,  248,  235,  236,  237,  158,  230,   87,
      231,   74,   74,   87,   87,  238,  239,   87,  241,  241,
       87,  249,   87,   87,   75,   87,   76,   77,   87,   87,
      250,   87,   87,  252,   87,   87,   87,   87,  251,   87,
       87,   87,  253,   87,   78,  254,   87,   87,  255,   87,
       87,   87,  256,   79,   87,   87,   77,   87,   87,  263,
       87,  265,   87,   87,  262,   87,  264,  266,  257,   87,

       87,  259,  260,  261,  270,  272,  274,  267,  269,  268,
      273,  277,   87,   87,   87,   87,  271,  278,  275,  276,
      280,  283,   87,  279,   87,   87,   87,  287,   87,   87,
       87,   87,  281,   87,   87,  282,   87,  286,   87,   87,
      284,  517,  285,  309,  318,  318,  318,  318,  291,  292,
      288,  517,  232,  232,  295,  290,  321,  293,  232,  232,
      299,  311,  289,  300,  321,  304,  296,   87,  303,  321,
      312,  313,  297,  307,  294,  298,  305,  302,  314,  301,
      308,  321,  314,  321,  321,  315,  306,  239,  239,  315,
       87,  239,  239,   87,  239,  239,  321,   87,  239,  239,

       75,  321,   76,   77,   75,  316,   76,   75,  319,   76,
       77,   75,   87,   76,  241,  241,  325,  320,  320,   87,
       78,   87,   87,   87,   78,   87,   87,   78,   87,   79,
       87,   78,   77,   79,  323,   87,   79,   87,  322,   77,
       79,   87,   87,   87,   87,   87,   87,  326,   87,   87,
       87,   87,   87,  324,   87,   87,   87,   87,  327,   87,
      330,   87,   87,  335,  328,   87,   87,  331,   87,  333,
       87,  336,   87,  329,  338,   87,  332,  342,  341,   87,
      345,  339,   87,  334,   87,   87,  346,   87,   87,   87,
       87,  337,  340,  344,  347,  357,  343,  348,  354,  517,

      350,  351,  349,  358,  353,  356,  352,  355,  366,  367,
      368,  311,  360,  369,  361,   87,   87,  359,  362,  374,
      235,  236,  365,  390,  370,  371,  372,  415,   74,   74,
      374,  393,  363,  373,   87,   87,  364,  375,  375,   74,
       74,   75,  518,   76,   77,   87,  376,  377,  378,  385,
      386,  379,   75,   87,   76,   87,  387,  388,  318,  318,
      391,   78,  380,  381,  382,  389,  320,  320,  396,   87,
       79,  383,   78,   77,  376,  377,  378,   87,  398,  379,
       87,   79,   87,   87,  366,  367,  368,   87,  395,  369,
      380,  381,  382,   87,   87,   87,  173,   87,   87,  383,

      370,  371,  372,   87,   87,  402,   87,   87,  392,  373,
       87,  394,   87,  397,   87,  399,   87,   87,   87,  400,
       87,   87,   87,   87,  425,   87,   87,  401,   87,   87,
      407,  408,  404,  232,  232,  428,   87,  403,  413,   87,
      411,   87,   87,  405,  517,  406,  412,  409,  410,  414,
      386,  419,  417,  418,  422,  420,  375,  375,  445,  437,
      437,  158,  416,  446,   87,  161,  162,  163,  448,   87,
      164,  421,   87,  447,   87,  429,  430,  431,  449,  452,
      432,  165,  166,  167,   87,   87,  450,  456,   87,  459,
      168,  433,  434,  435,  439,  430,  440,   87,   87,  441,

      436,   87,  428,  451,  464,  454,  457,  242,  453,   87,
      442,  434,  443,  465,  465,  455,  318,  318,  466,  444,
      458,   87,  318,  318,   87,  470,   87,  467,  467,   87,
      460,  366,  367,  368,  437,  437,  369,  437,  437,  461,
      463,   87,  462,   87,   87,   87,   87,  370,  371,  372,
       87,   87,   87,  487,  485,   87,  373,   87,  490,  472,
      486,  473,  465,  465,  474,   87,  488,  467,  467,  491,
       87,  475,  489,  517,  476,   87,  477,  517,  492,  492,
      480,  481,  512,  478,  493,  485,  494,  484,  513,  495,
      499,  500,  479,  483,  465,  465,  366,  488,  368,  517,

      496,  369,  497,  517,  502,  482,  504,  504,  515,  498,
      501,  517,  370,  514,  372,  506,  430,  507,  465,  465,
      508,  373,  492,  492,   87,  516,  504,  504,  512,  492,
      492,  509,  434,  510,  504,  504,   87,  492,  492,  429,
      511,  431,   87,  519,  432,  520,  471,  471,  521,  471,
      471,  471,  471,  505,  503,  433,   87,  435,   87,  522,
       87,  523,   87,   87,  436,   87,   87,   87,  524,   55,
       87,   55,   55,   60,   87,   60,   60,   88,   88,  159,
       87,  159,  159,  160,   87,  160,  160,  233,   87,  233,
      233,   87,   87,  471,  471,  471,  471,  471,  471,  468,

      468,  469,  468,  468,  468,  469,  468,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,  438,  426,  426,  427,  426,  426,  426,  427,
      426,  423,  423,  424,  423,  423,  423,  424,  423,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
      384,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,  317,  310,   87,   87,   87,
       88,  245,  245,  246,  245,  245,  245,  246,  245,  244,
      243,  240,  240,  240,  240,  240,  240,  240,   87,   87,
       87,   87,  173,  172,  171,  156,  148,  145,   56,   56,

       90,   89,   87,   86,   65,   57,   56,   54,  525,    3,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525
    } ;

static const flex_int16_t yy_chk[1180] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    9,
       10,   14,   16,   32,   18,   41,   10,   19,   34,   18,
       16,   14,   20,   44,    9,   18,   19,   19,   23,   23,
       33,   20,   20,   24,   24,   25,   25,   10,   37,   19,

       10,   19,   19,   38,   20,   32,   20,   35,   49,   34,
       41,   36,   75,   39,   40,   42,   34,  181,   44,   19,
       34,   33,   32,   34,   20,   48,   41,   43,   19,   37,
       51,   19,  531,   20,   46,   33,   91,   37,   33,   75,
       37,   45,   35,   37,   47,   33,   49,   42,   38,   39,
      181,   76,   35,   36,   78,   36,   39,   39,   43,   40,
      524,   42,   39,   36,   48,   36,   42,   42,   63,   70,
       48,   76,   46,   45,   51,   43,   45,   63,   43,   45,
       45,   78,   46,   47,   93,   91,   47,   61,   47,   46,
       94,   45,   95,   47,   45,   70,   61,   61,   96,   63,

       63,   97,  103,   98,   74,   73,   73,   73,   99,   79,
       73,  101,   63,   74,   74,  100,   63,  102,   63,  104,
       63,   73,   73,   73,  107,  105,   74,   95,   74,   79,
       73,  106,  108,   93,   98,   94,  110,  109,   98,   99,
      111,  113,  114,  117,  101,  116,   74,  101,   96,  118,
       97,  103,  121,  101,  119,   74,  123,  127,  120,  100,
      105,  124,  122,  125,  129,  130,  107,  126,  102,  132,
      104,  133,  134,  135,  128,  137,  131,  106,  136,  140,
      138,  106,  109,  523,  110,  522,  108,  113,  139,  116,
      111,  118,  114,  120,  119,  125,  117,  122,  126,  141,

      124,  142,  121,  126,  123,  128,  124,  131,  132,  129,
      133,  157,  127,  138,  145,  145,  157,  126,  174,  135,
      137,  130,  136,  134,  131,  146,  139,  140,  175,  138,
      176,  170,  147,  170,  146,  146,  148,  157,  141,  156,
      142,  147,  147,  178,  177,  148,  148,  179,  156,  156,
      180,  170,  182,  183,  147,  184,  147,  147,  185,  187,
      170,  186,  188,  175,  189,  190,  191,  193,  174,  192,
      194,  196,  176,  197,  147,  177,  199,  198,  178,  195,
      200,  202,  179,  147,  204,  203,  147,  206,  208,  185,
      207,  187,  209,  211,  184,  210,  186,  188,  180,  213,

      216,  182,  183,  183,  192,  194,  196,  189,  191,  190,
      195,  199,  214,  215,  217,  219,  193,  200,  197,  198,
      203,  207,  220,  202,  218,  222,  221,  211,  223,  224,
      226,  228,  204,  225,  227,  206,  229,  210,  231,  230,
      208,  521,  209,  232,  244,  244,  245,  245,  216,  217,
      213,  520,  232,  232,  219,  215,  247,  218,  310,  310,
      222,  234,  214,  223,  248,  227,  219,  259,  226,  249,
      234,  234,  220,  230,  218,  221,  228,  225,  235,  224,
      231,  250,  236,  247,  248,  238,  229,  235,  235,  239,
      251,  236,  236,  254,  238,  238,  249,  260,  239,  239,

      235,  250,  235,  235,  236,  241,  236,  238,  246,  238,
      238,  239,  258,  239,  241,  241,  259,  246,  246,  261,
      235,  262,  263,  264,  236,  265,  268,  238,  271,  235,
      269,  239,  235,  236,  254,  270,  238,  272,  251,  238,
      239,  273,  276,  274,  277,  280,  281,  260,  282,  284,
      283,  285,  287,  258,  288,  286,  291,  293,  261,  292,
      264,  295,  296,  271,  262,  289,  290,  265,  294,  269,
      297,  272,  300,  263,  274,  302,  268,  281,  280,  303,
      284,  276,  304,  270,  305,  306,  285,  308,  324,  329,
      356,  273,  277,  283,  286,  296,  282,  287,  293,  519,

      289,  290,  288,  297,  292,  295,  291,  294,  309,  309,
      309,  311,  302,  309,  303,  515,  327,  300,  304,  312,
      311,  311,  308,  324,  309,  309,  309,  356,  312,  312,
      313,  329,  305,  309,  322,  333,  306,  314,  314,  313,
      313,  312,  513,  312,  312,  338,  314,  314,  314,  318,
      319,  314,  313,  331,  313,  341,  319,  320,  318,  318,
      327,  312,  314,  314,  314,  322,  320,  320,  333,  334,
      312,  314,  313,  312,  315,  315,  315,  328,  338,  315,
      330,  313,  339,  340,  316,  316,  316,  342,  331,  316,
      315,  315,  315,  343,  344,  345,  316,  346,  347,  315,

      316,  316,  316,  348,  349,  341,  351,  354,  328,  316,
      353,  330,  357,  334,  358,  339,  355,  359,  361,  340,
      362,  363,  391,  364,  375,  389,  392,  340,  393,  390,
      346,  347,  343,  375,  375,  384,  394,  342,  354,  407,
      351,  398,  403,  344,  511,  345,  353,  348,  349,  355,
      386,  361,  358,  359,  364,  362,  374,  374,  389,  386,
      386,  384,  357,  390,  396,  374,  374,  374,  392,  399,
      374,  363,  404,  391,  400,  385,  385,  385,  393,  398,
      385,  374,  374,  374,  401,  406,  394,  403,  409,  407,
      374,  385,  385,  385,  388,  388,  388,  413,  422,  388,

      385,  419,  428,  396,  424,  400,  404,  428,  399,  445,
      388,  388,  388,  424,  424,  401,  426,  426,  427,  388,
      406,  451,  425,  425,  453,  437,  447,  427,  427,  450,
      409,  425,  425,  425,  437,  437,  425,  438,  438,  413,
      422,  455,  419,  454,  456,  457,  459,  425,  425,  425,
      460,  461,  462,  465,  464,  477,  425,  481,  467,  445,
      464,  447,  465,  465,  450,  483,  466,  467,  467,  469,
      484,  451,  466,  510,  453,  501,  454,  509,  469,  469,
      457,  459,  491,  455,  470,  485,  470,  462,  491,  470,
      477,  481,  456,  461,  485,  485,  487,  488,  487,  508,

      470,  487,  470,  507,  484,  460,  488,  488,  501,  470,
      483,  506,  487,  492,  487,  490,  490,  490,  503,  503,
      490,  487,  492,  492,  502,  504,  505,  505,  512,  518,
      518,  490,  490,  490,  504,  504,  500,  512,  512,  514,
      490,  514,  499,  516,  514,  516,  498,  497,  516,  496,
      495,  494,  493,  489,  486,  514,  482,  514,  480,  516,
      479,  516,  478,  476,  514,  475,  474,  473,  516,  526,
      472,  526,  526,  527,  463,  527,  527,  528,  528,  529,
      458,  529,  529,  530,  452,  530,  530,  532,  449,  532,
      532,  448,  446,  444,  443,  442,  441,  440,  439,  436,

      435,  434,  433,  432,  431,  430,  429,  421,  420,  418,
      417,  416,  415,  414,  412,  411,  410,  408,  405,  402,
      397,  395,  387,  383,  382,  381,  380,  379,  378,  377,
      376,  373,  372,  371,  370,  369,  368,  367,  366,  365,
      360,  352,  350,  337,  336,  335,  332,  326,  325,  323,
      317,  307,  301,  299,  298,  279,  278,  275,  267,  266,
      257,  256,  255,  253,  252,  243,  233,  212,  205,  201,
      173,  168,  167,  166,  165,  164,  163,  162,  161,  160,
      158,  155,  154,  153,  152,  151,  150,  149,  115,  112,
       92,   88,   87,   85,   80,   64,   62,   60,   56,   55,

       31,   29,   27,   26,   13,    8,    7,    6,    3,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525,  525,
      525,  525,  525,  525,  525,  525,  525,  525,  525
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/Scanner/c-sharp.l"
/* Scanner for a C# 6.0 compiler generated with Flex */
#define YY_NO_INPUT 1
#line 8 "src/Scanner/c-sharp.l"

#include "pch.h"
#include "parser.h"

#define SBYTE_MAX_VALUE  127
#define BYTE_MAX_VALUE   256
#define SHORT_MAX_VALUE  32767
#define USHORT_MAX_VALUE 65535
#define INT_MAX_VALUE    2147483647
#define UINT_MAX_VALUE   4294967295
#define LONG_MAX_VALUE   9223372036854775807

int CheckIntType(long long value, char *suffix);
long long TreatIntString(char *text);
long long TreatHexString(char *text);
int CheckRealType(char *text);

#line 900 "src/Scanner/scanner.c"
/* character_literal '\''{character}'\''

character .|{simple_escape_sequence}|{hexadecimal_escape_sequence}

simple_escape_sequence '\\\''|'\\"'|'\\\\'|'\\0'|'\\a'|'\\b'|'\\f'|'\\n'|'\\r'|'\\t'|'\\v'

hexadecimal_escape_sequence "\\x"([0-9]|[a-f]|[A-F])([0-9]|[a-f]|[A-F])?([0-9]|[a-f]|[A-F])?([0-9]|[a-f]|[A-F])? */
/*{identifier_with_at} { printf("IDENTIFIER\n");return IDENTIFIER; }*/
#line 909 "src/Scanner/scanner.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 50 "src/Scanner/c-sharp.l"


#line 1127 "src/Scanner/scanner.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 526 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1110 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 52 "src/Scanner/c-sharp.l"
{ /* ignoring white spaces */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 53 "src/Scanner/c-sharp.l"
{ /* singleline comments are ignored*/ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 54 "src/Scanner/c-sharp.l"
{ /* multiline comments are ignored */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 57 "src/Scanner/c-sharp.l"
{ printf("START_PAR\n");return START_PAR; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 58 "src/Scanner/c-sharp.l"
{ printf("END_PAR\n");return END_PAR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 59 "src/Scanner/c-sharp.l"
{ printf("START_CURLY\n");return START_CURLY; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 60 "src/Scanner/c-sharp.l"
{ printf("END_CURLY\n");return END_CURLY; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 61 "src/Scanner/c-sharp.l"
{ printf("START_BRCKT\n");return START_BRCKT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 62 "src/Scanner/c-sharp.l"
{ printf("END_BRCKT\n");return END_BRCKT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 63 "src/Scanner/c-sharp.l"
{ printf("ADD\n");return ADD; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 64 "src/Scanner/c-sharp.l"
{ printf("SUB\n");return SUB; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 65 "src/Scanner/c-sharp.l"
{ printf("DIV\n");return DIV; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 66 "src/Scanner/c-sharp.l"
{ printf("MUL\n");return MUL; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 67 "src/Scanner/c-sharp.l"
{ printf("MOD\n");return MOD; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 68 "src/Scanner/c-sharp.l"
{ printf("NOT\n");return NOT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 69 "src/Scanner/c-sharp.l"
{ printf("QMARK\n");return QMARK; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 70 "src/Scanner/c-sharp.l"
{ printf("BIT_XOR\n");return BIT_XOR; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 71 "src/Scanner/c-sharp.l"
{ printf("COLON\n");return COLON; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 72 "src/Scanner/c-sharp.l"
{ printf("SEMI\n");return SEMI; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 73 "src/Scanner/c-sharp.l"
{ printf("COMMA\n");return COMMA; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 74 "src/Scanner/c-sharp.l"
{ printf("DOT\n");return DOT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 75 "src/Scanner/c-sharp.l"
{ printf("ASSIGN\n");return ASSIGN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 76 "src/Scanner/c-sharp.l"
{ printf("LESS_THEN\n");return LESS_THEN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 77 "src/Scanner/c-sharp.l"
{ printf("GREATER_THEN\n");return GREATER_THEN; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 78 "src/Scanner/c-sharp.l"
{ printf("BIT_AND\n");return BIT_AND; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 79 "src/Scanner/c-sharp.l"
{ printf("BIT_OR\n");return BIT_OR; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 80 "src/Scanner/c-sharp.l"
{ printf("BIT_NOT\n");return BIT_NOT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 81 "src/Scanner/c-sharp.l"
{ printf("EQ\n");return EQ; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 82 "src/Scanner/c-sharp.l"
{ printf("GEQ\n");return GEQ; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 83 "src/Scanner/c-sharp.l"
{ printf("LEQ\n");return LEQ; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 84 "src/Scanner/c-sharp.l"
{ printf("NOT_EQ\n");return NOT_EQ; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 85 "src/Scanner/c-sharp.l"
{ printf("ADD_ASSIGN\n");return ADD_ASSIGN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 86 "src/Scanner/c-sharp.l"
{ printf("SUB_ASSIGN\n");return SUB_ASSIGN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 87 "src/Scanner/c-sharp.l"
{ printf("MUL_ASSIGN\n");return MUL_ASSIGN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 88 "src/Scanner/c-sharp.l"
{ printf("DIV_ASSIGN\n");return DIV_ASSIGN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 89 "src/Scanner/c-sharp.l"
{ printf("MOD_ASSIGN\n");return MOD_ASSIGN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 90 "src/Scanner/c-sharp.l"
{ printf("BIT_AND_ASSIGN\n");return BIT_AND_ASSIGN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 91 "src/Scanner/c-sharp.l"
{ printf("BIT_OR_ASSIGN\n");return BIT_OR_ASSIGN; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 92 "src/Scanner/c-sharp.l"
{ printf("BIT_XOR_ASSIGN\n");return BIT_XOR_ASSIGN; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 93 "src/Scanner/c-sharp.l"
{ printf("LEFT_SHIFT\n");return LEFT_SHIFT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 94 "src/Scanner/c-sharp.l"
{ printf("RIGHT_SHIFT\n");return RIGHT_SHIFT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 95 "src/Scanner/c-sharp.l"
{ printf("AND\n");return AND; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 96 "src/Scanner/c-sharp.l"
{ printf("OR\n");return OR; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 97 "src/Scanner/c-sharp.l"
{ printf("DOUBLE_QMARK\n");return DOUBLE_QMARK; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 98 "src/Scanner/c-sharp.l"
{ printf("INCREMENT\n");return INCREMENT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 99 "src/Scanner/c-sharp.l"
{ printf("DECREMENT\n");return DECREMENT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 100 "src/Scanner/c-sharp.l"
{ printf("LAMBDA\n");return LAMBDA; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 101 "src/Scanner/c-sharp.l"
{ printf("LEFT_SHIFT_ASSIGN\n");return LEFT_SHIFT_ASSIGN; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 102 "src/Scanner/c-sharp.l"
{ printf("RIGHT_SHIFT_ASSIGN\n");return RIGHT_SHIFT_ASSIGN; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 103 "src/Scanner/c-sharp.l"
{ printf("ABSTRACT\n");return ABSTRACT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 104 "src/Scanner/c-sharp.l"
{ printf("AS\n");return AS; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 105 "src/Scanner/c-sharp.l"
{ printf("BASE\n");return BASE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 106 "src/Scanner/c-sharp.l"
{ printf("BOOL_TYPE\n");return BOOL_TYPE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 107 "src/Scanner/c-sharp.l"
{ printf("BREAK\n");return BREAK; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 108 "src/Scanner/c-sharp.l"
{ printf("BYTE_TYPE\n");return BYTE_TYPE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 109 "src/Scanner/c-sharp.l"
{ printf("CASE\n");return CASE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 110 "src/Scanner/c-sharp.l"
{ printf("CHAR_TYPE\n");return CHAR_TYPE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 111 "src/Scanner/c-sharp.l"
{ printf("CHECKED\n");return CHECKED; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 112 "src/Scanner/c-sharp.l"
{ printf("CLASS\n");return CLASS; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 113 "src/Scanner/c-sharp.l"
{ printf("CONST\n");return CONST; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 114 "src/Scanner/c-sharp.l"
{ printf("CONTINUE\n");return CONTINUE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 115 "src/Scanner/c-sharp.l"
{ printf("DECIMAL_TYPE\n");return DECIMAL_TYPE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 116 "src/Scanner/c-sharp.l"
{ printf("DEFAULT\n");return DEFAULT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 117 "src/Scanner/c-sharp.l"
{ printf("DELEGATE\n");return DELEGATE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 118 "src/Scanner/c-sharp.l"
{ printf("DO\n");return DO; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 119 "src/Scanner/c-sharp.l"
{ printf("DOUBLE_TYPE\n");return DOUBLE_TYPE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 120 "src/Scanner/c-sharp.l"
{ printf("ELSE\n");return ELSE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 121 "src/Scanner/c-sharp.l"
{ printf("ENUM\n");return ENUM; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 122 "src/Scanner/c-sharp.l"
{ printf("EVENT\n");return EVENT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 123 "src/Scanner/c-sharp.l"
{ printf("EXPLICIT\n");return EXPLICIT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 124 "src/Scanner/c-sharp.l"
{ printf("EXTERN\n");return EXTERN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 125 "src/Scanner/c-sharp.l"
{ printf("FALSE_VAL\n");return FALSE_VAL; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 126 "src/Scanner/c-sharp.l"
{ printf("FIXED\n");return FIXED; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 127 "src/Scanner/c-sharp.l"
{ printf("FLOAT_TYPE\n");return FLOAT_TYPE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 128 "src/Scanner/c-sharp.l"
{ printf("FOR\n");return FOR; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 129 "src/Scanner/c-sharp.l"
{ printf("FOREACH\n");return FOREACH; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 130 "src/Scanner/c-sharp.l"
{ printf("GOTO\n");return GOTO; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 131 "src/Scanner/c-sharp.l"
{ printf("IF\n");return IF; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 132 "src/Scanner/c-sharp.l"
{ printf("IMPLICIT\n");return IMPLICIT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 133 "src/Scanner/c-sharp.l"
{ printf("IN\n");return IN; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 134 "src/Scanner/c-sharp.l"
{ printf("INT_TYPE\n");return INT_TYPE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 135 "src/Scanner/c-sharp.l"
{ printf("INTERFACE\n");return INTERFACE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 136 "src/Scanner/c-sharp.l"
{ printf("INTERNAL\n");return INTERNAL; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 137 "src/Scanner/c-sharp.l"
{ printf("IS\n");return IS; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 138 "src/Scanner/c-sharp.l"
{ printf("LONG_TYPE\n");return LONG_TYPE; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 139 "src/Scanner/c-sharp.l"
{ printf("NEW\n");return NEW; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 140 "src/Scanner/c-sharp.l"
{ printf("NULL_VALUE\n");return NULL_VALUE; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 141 "src/Scanner/c-sharp.l"
{ printf("OBJECT\n");return OBJECT; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 142 "src/Scanner/c-sharp.l"
{ printf("OPERATOR\n");return OPERATOR; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 143 "src/Scanner/c-sharp.l"
{ printf("OUT\n");return OUT; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 144 "src/Scanner/c-sharp.l"
{ printf("OVERRIDE\n");return OVERRIDE; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 145 "src/Scanner/c-sharp.l"
{ printf("PARAMS\n");return PARAMS; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 146 "src/Scanner/c-sharp.l"
{ printf("PRIVATE\n");return PRIVATE; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 147 "src/Scanner/c-sharp.l"
{ printf("PROTECTED\n");return PROTECTED; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 148 "src/Scanner/c-sharp.l"
{ printf("PUBLIC\n");return PUBLIC; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 149 "src/Scanner/c-sharp.l"
{ printf("READONLY\n");return READONLY; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 150 "src/Scanner/c-sharp.l"
{ printf("REF\n");return REF; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 151 "src/Scanner/c-sharp.l"
{ printf("RETURN\n");return RETURN; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 152 "src/Scanner/c-sharp.l"
{ printf("SBYTE_TYPE\n");return SBYTE_TYPE; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 153 "src/Scanner/c-sharp.l"
{ printf("SEALED\n");return SEALED; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 154 "src/Scanner/c-sharp.l"
{ printf("SHORT_TYPE\n");return SHORT_TYPE; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 155 "src/Scanner/c-sharp.l"
{ printf("SIZEOF\n");return SIZEOF; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 156 "src/Scanner/c-sharp.l"
{ printf("STACKALLOC\n");return STACKALLOC; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 157 "src/Scanner/c-sharp.l"
{ printf("STATIC\n");return STATIC; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 158 "src/Scanner/c-sharp.l"
{ printf("STRING_TYPE\n");return STRING_TYPE; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 159 "src/Scanner/c-sharp.l"
{ printf("STRUCT\n");return STRUCT; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 160 "src/Scanner/c-sharp.l"
{ printf("SWITCH\n");return SWITCH; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 161 "src/Scanner/c-sharp.l"
{ printf("THIS\n");return THIS; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 162 "src/Scanner/c-sharp.l"
{ printf("TRUE_VAL\n");return TRUE_VAL; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 163 "src/Scanner/c-sharp.l"
{ printf("TYPEOF\n");return TYPEOF; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 164 "src/Scanner/c-sharp.l"
{ printf("UINT_TYPE\n");return UINT_TYPE; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 165 "src/Scanner/c-sharp.l"
{ printf("ULONG_TYPE\n");return ULONG_TYPE; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 166 "src/Scanner/c-sharp.l"
{ printf("UNCHECKED\n");return UNCHECKED; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 167 "src/Scanner/c-sharp.l"
{ printf("UNSAFE\n");return UNSAFE; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 168 "src/Scanner/c-sharp.l"
{ printf("USHORT_TYPE\n");return USHORT_TYPE; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 169 "src/Scanner/c-sharp.l"
{ printf("VIRTUAL\n");return VIRTUAL; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 170 "src/Scanner/c-sharp.l"
{ printf("VOID\n");return VOID; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 171 "src/Scanner/c-sharp.l"
{ printf("WHILE\n");return WHILE; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 173 "src/Scanner/c-sharp.l"
{ printf("IDENTIFIER\n");return IDENTIFIER; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 175 "src/Scanner/c-sharp.l"
{ long long value = atoll(yytext); return CheckIntType(value, NULL); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 176 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatIntString(yytext)); return CheckIntType(value, "U"); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 177 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatIntString(yytext)); return CheckIntType(value, "L"); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 178 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatIntString(yytext)); return CheckIntType(value, "UL"); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 180 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatHexString(yytext)); return CheckIntType(value, NULL); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 181 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatHexString(yytext)); return CheckIntType(value, "U"); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 182 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatHexString(yytext)); return CheckIntType(value, "L"); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 183 "src/Scanner/c-sharp.l"
{ long long value = atoll(TreatHexString(yytext)); return CheckIntType(value, "UL"); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 185 "src/Scanner/c-sharp.l"
{ return CheckRealType(yytext); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 187 "src/Scanner/c-sharp.l"
{ printf("CHAR_VAL");return CHAR_VAL; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 189 "src/Scanner/c-sharp.l"
{ printf("ENTER");return ENTER; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 191 "src/Scanner/c-sharp.l"
{ printf("STRING_VAL");return STRING_VAL; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 193 "src/Scanner/c-sharp.l"
ECHO;
	YY_BREAK
#line 1845 "src/Scanner/scanner.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 526 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 526 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 525);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 193 "src/Scanner/c-sharp.l"


int CheckIntType(long long value, char *suffix)
{
    value = llabs(value);

    // If there's no suffix telling which type it is:
    if (suffix == NULL)
    {
        // Comparing the value with the maximum size of each type to define the type that must be returned:
        if (value <= SBYTE_MAX_VALUE)
        {
            printf("SBYTE_VAL\n");
            return SBYTE_VAL;
        }
        else if (value <= BYTE_MAX_VALUE)
        {
            printf("BYTE_VAL\n");
            return BYTE_VAL;
        }
        else if (value <= SHORT_MAX_VALUE)
        {
            printf("SHORT_VAL\n");
            return SHORT_VAL;
        }
        else if (value <= USHORT_MAX_VALUE)
        {
            printf("USHORT_VAL\n");
            return USHORT_VAL;
        }
        else if (value <= INT_MAX_VALUE)
        {
            printf("INT_VAL\n");
            return INT_VAL;
        }
        else if (value <= UINT_MAX_VALUE)
        {
            printf("UINT_VAL\n");
            return UINT_VAL;
        }
        else if (value <= LONG_MAX_VALUE)
        {
            printf("LONG_VAL\n");
            return LONG_VAL;
        }
        else
        {
            printf("ULONG_VALUE\n");
            return ULONG_VAL;
        }
    }
    else if (strcmp(suffix, "U") == 0)
        goto start_from_unsigned;
    else if (strcmp(suffix, "L") == 0)
        goto start_from_long;
    else if (strcmp(suffix, "Ul") == 0)
        goto start_from_unsigned;

    start_from_unsigned:
    if (value <= UINT_MAX_VALUE)
    {
        printf("UINT_VAL\n");
        return UINT_VAL;
    }
    
    start_from_long:
    if (value > UINT_MAX_VALUE)
    {
        printf("LONG_VAL\n");
        return LONG_VAL;
    }
    
    start_from_ulong:
    if (value > LONG_MAX_VALUE)
    {
        printf("ULONG_VALUE\n");
        return ULONG_VAL;
    }

    return -1;
}

#define IS_SIGN(c) (c == '+' || c == '-')
#define IS_DIGIT(c) ('0' <= c && c <= '9')
#define IS_HIGHCASE_HEX(c) ('A' <= c && c <= 'F')
#define IS_LOWCASE_HEX(c) ('a' <= c && c <= 'f')
#define CONVERT_HIGHCASE_HEX(c) (c - 55)
#define CONVERT_LOWCASE_HEX(c) (c - 87)

long long TreatIntString(char *text)
{
    char *letterPtr = text;
    int digits = 0;
    while (IS_DIGIT(*letterPtr) || IS_SIGN(*letterPtr))
    {
        ++digits;
        ++letterPtr;
    }
    char *number = malloc(digits * sizeof(char));
    number = strncpy(number, text, digits * sizeof(char));
    long long result = atoll(number);
    free(number);
    return result;
}

long long TreatHexString(char *text)
{
    char *letter = text;
    int digits = 0;
    long long result = 0;
    while (IS_DIGIT(*letter) || IS_HIGHCASE_HEX(*letter) || IS_LOWCASE_HEX(*letter) || *letter == 'x' || *letter == 'X' || IS_SIGN(*letter))
    {
        ++digits;
        ++letter;
    }
    char *number = malloc(digits * sizeof(char));
    number = strncpy(number, text, digits * sizeof(char));
    result = (long long)strtol(number, NULL, 0);
    return result;
}

#define IS_EXP_SYMBOL(c) (c == 'e' || c == 'E')
#define IS_FLOAT_SUFFIX(c) (c == 'f' || c == 'E')
#define IS_DOUBLE_SUFFIX(c) (c == 'd' || c == 'D')
#define IS_DECIMAL_SUFFIX(c) (c == 'm' || c == 'M')
#define IS_REAL_CHAR(c) IS_DIGIT(c) || (c == '.') || IS_SIGN(c) || IS_EXP_SYMBOL(c) || IS_FLOAT_SUFFIX(c) || IS_DOUBLE_SUFFIX(c) || IS_DECIMAL_SUFFIX(c)

int CheckRealType(char *text)
{
    /**
        Divide text in the following parts:
            -> Number sign (optional);
            -> Integer part of the number;
            -> Fractional part of the number;
            -> Exponent symbol (optional);
            -> Exponent sign (optional);
            -> Exponent number (optional);
            -> Type suffix (optional);

        Return possibilities:
            FLOAT_VAL
            DOUBLE_VAL
            DECIMAL_VAL
    */
    char *letter = text;
    long double sign = 1;
    long double value = 0;
    int chars = 0;
    int offset = 0;
    while (IS_REAL_CHAR(*letter))
    {
        if (IS_SIGN(*letter)) ++offset;
        else if (IS_DIGIT(*letter) || *letter == '.' || IS_EXP_SYMBOL(*letter))
        {
            ++chars;
            ++letter;
        }
        else if (IS_FLOAT_SUFFIX(*letter) || IS_DOUBLE_SUFFIX(*letter) || IS_DECIMAL_SUFFIX(*letter)) break;
    }
    char *number = malloc(chars * sizeof(char));
    number = strncpy(number, text + offset, chars * sizeof(char));
    value = strtold(number, NULL);
    if (value <= FLT_MAX)
    {
        printf("FLOAT_VAL\n");
        return FLOAT_VAL;
    }
    else if (value > FLT_MAX && value <= DBL_MAX)
    {
        printf("DOUBLE_VAL\n");
        return DOUBLE_VAL;
    }
    else
    {
        printf("DECIMAL_VAL\n");
        return DECIMAL_VAL;
    }
}

